// ============================================================================
// slidesGenerator - 设计 tab 厚版演示稿生成 service（二期 MVP）
// ============================================================================
// 把现有 PPT 引擎（src/host/tools/media/ppt/*）的「确定性大纲 → 真排版 deck」核心
// 从 agent 工具 executePptGenerate 中抽出，供设计 tab IPC 直调——不经工具调用语义、
// 不调 LLM/研究/配图/VLM（那些是付费可选增强，留待后续增量）。
//
// 复刻 pptGenerate.ts:498-708 的 legacy（SlideData[]）路径，去掉 ToolContext/
// modelCallback/artifact/权限耦合。引擎纯核函数直接 import 复用，零拷贝。
// ============================================================================

import type PptxGenJS from 'pptxgenjs';
import type { ChartMode, SlideData, SlideImage, ThemeConfig } from '../../tools/media/ppt/types';
import { getThemeConfig } from '../../tools/media/ppt/themes';
import { outlineToSlideData, parseContentToSlides } from '../../tools/media/ppt/parser';
import { getActiveBrandSync } from './brandRegistry';
import { themeConfigFromBrand } from './brandTheme';
import { registerSlideMasters } from '../../tools/media/ppt/slideMasters';
import { selectMasterAndLayout, fillSlide, resetLayoutRotation } from '../../tools/media/ppt/layouts';

// pptxgenjs 是 CJS——走 require 取构造器（与 pptGenerate / pptxExport 同款）。
type PptxGenJSConstructor = new () => PptxGenJS;
function getPptxGenJS(): PptxGenJSConstructor {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const moduleValue: unknown = require('pptxgenjs');
  return moduleValue as PptxGenJSConstructor;
}

const DEFAULT_SLIDES_COUNT = 10;
const DEFAULT_THEME = 'neon-green';

/**
 * 主题解析（增强 #3 品牌注入）：显式 theme 优先（用户主动选主题）；否则若有 active 品牌
 * 契约则据品牌色板/字体构造主题（「我的品牌」强制注入）；都没有则默认主题。
 */
function resolveTheme(explicitTheme?: string): ThemeConfig {
  if (explicitTheme) return getThemeConfig(explicitTheme);
  const brand = getActiveBrandSync();
  return brand ? themeConfigFromBrand(brand) : getThemeConfig(DEFAULT_THEME);
}

export interface SlidesDeckInput {
  /** 演示稿主题 / 需求描述。slides 直传时可省（取首页标题为 deck 标题）。 */
  topic?: string;
  /** 期望页数（含封面/结尾），默认 10。 */
  slidesCount?: number;
  /** 主题样式键，未知值回退默认；默认 'neon-green'。 */
  theme?: string;
  /** 可选 Markdown 正文：提供则按它切页，优先于 topic 模板大纲。 */
  content?: string;
  /** 已编辑的大纲（SlideData[]）：提供且非空则直接据此排版，优先于 content/topic。 */
  slides?: SlideData[];
  /** AI 配图（增强 #4）：按 slide_index 喂进 fillSlide，对应页走图文母版。 */
  images?: SlideImage[];
}

/**
 * 生成确定性大纲（SlideData[]，SCQA 模板，不调 LLM/不付费）。
 * 供设计 tab「生成大纲 → 编辑 → 生成演示稿」流程的第一步。
 */
export function buildSlidesOutline(topic: string, slidesCount?: number): SlideData[] {
  const t = (topic ?? '').trim();
  if (!t) {
    throw new Error('生成大纲需要主题（topic 不能为空）');
  }
  const count = slidesCount && slidesCount > 0 ? slidesCount : DEFAULT_SLIDES_COUNT;
  return outlineToSlideData(t, count);
}

export interface SlidesDeckResult {
  /** PPTX nodebuffer（调用方负责写盘 / 下载）。 */
  buffer: Buffer;
  /** 实际生成的页数。 */
  slidesCount: number;
}

/**
 * 生成厚版演示稿 deck（真排版引擎，非图片塞 PPT）。
 * 当前 MVP：确定性大纲（或 Markdown 切页）→ 注册 8 类 master → 逐页 fillSlide → nodebuffer。
 * 不调任何付费模型；topic 为空抛可读错误。
 */
export async function generateSlidesDeck(input: SlidesDeckInput): Promise<SlidesDeckResult> {
  const topic = (input.topic ?? '').trim();
  const hasSlides = Array.isArray(input.slides) && input.slides.length > 0;
  if (!topic && !hasSlides) {
    throw new Error('生成演示稿需要主题或大纲（topic 或 slides 至少其一）');
  }
  const count = input.slidesCount && input.slidesCount > 0 ? input.slidesCount : DEFAULT_SLIDES_COUNT;
  const themeConfig = resolveTheme(input.theme);

  // 内容通道优先级：已编辑大纲 slides > Markdown content > topic 模板大纲。
  const content = input.content?.trim();
  const slides: SlideData[] = hasSlides
    ? input.slides!
    : content
      ? parseContentToSlides(content, count)
      : outlineToSlideData(topic, count);

  const deckTitle = topic || slides[0]?.title || 'Presentation';
  const Pptx = getPptxGenJS();
  const pptx = new Pptx();
  pptx.author = 'Agent Neo';
  pptx.title = deckTitle;
  pptx.subject = deckTitle;
  pptx.company = 'Generated by Agent Neo';

  // ⑥ 注册 master + ⑦ 逐页组装（复刻 pptGenerate legacy 路径，无图片/图表注入）。
  registerSlideMasters(pptx, themeConfig);
  resetLayoutRotation();

  const allImages: SlideImage[] = input.images ?? [];
  for (let i = 0; i < slides.length; i++) {
    const slideData = slides[i];
    const slideImages = allImages.filter((img) => img.slide_index === i);
    const { master, layout, chartData } = selectMasterAndLayout(
      slideData,
      slideImages.length > 0,
      'auto' as ChartMode,
    );
    const slide = pptx.addSlide({ masterName: master });
    fillSlide(pptx, slide, slideData, themeConfig, layout, i, chartData, slideImages);
  }

  const out = await pptx.write({ outputType: 'nodebuffer' });
  return { buffer: Buffer.from(out as Uint8Array), slidesCount: slides.length };
}
