import { describe, expect, it } from 'vitest';
import { acceptInvitation, createIdentity, decryptFrame, encodeInvitation, encryptFrame, issueInvitation, PairingError, PairingRegistry, loadIdentity, saveIdentity, verifyHandshake, signHandshake } from '../../../packages/mobile/src/pairing/protocol';
const store = () => { let value: string | null = null; return { get: async (_key?: string) => value, set: async (_key: string, v: string) => { value = v; } }; };
describe('mobile pairing spike MP-01..04', () => {
 it('normal handshake and persistence', async () => { const h=createIdentity('host'); const p=createIdentity('phone'); const i=issueInvitation(h,1000,100); const r=acceptInvitation(i,h,p,200); expect(r.sessionKey).toHaveLength(32); const x=`${h.id}|${p.id}|1`; expect(verifyHandshake(h,x,signHandshake(h,x))).toBe(true); const s=store(); await saveIdentity(s,p); expect((await loadIdentity(s))?.id).toBe('phone'); });
 it.each([['expired',()=>acceptInvitation(issueInvitation(createIdentity('h'),10,0),createIdentity('h'),createIdentity('p'),11),'INVITE_EXPIRED'],['replay',()=>{const h=createIdentity('h');const p=createIdentity('p');const i=issueInvitation(h);acceptInvitation(i,h,p);return acceptInvitation(i,h,p)},'INVITE_REPLAYED'],['identity replacement',()=>{const h=createIdentity('h');return acceptInvitation(issueInvitation(h),createIdentity('other'),createIdentity('p'))},'IDENTITY_MISMATCH']] as const)('rejects %s',(_n,fn,c)=>expect(fn).toThrowError(new PairingError(c)));
 it('rejects tamper replay downgrade',()=>{const k=Buffer.alloc(32,7);const f=encryptFrame(k,'phone',1,'secret');expect(decryptFrame(k,f,'phone',0).plaintext).toBe('secret');expect(()=>decryptFrame(k,f,'phone',1)).toThrowError(new PairingError('FRAME_REPLAYED'));expect(()=>decryptFrame(k,{...f,ciphertext:f.ciphertext.slice(0,-2)+'AA'},'phone',0)).toThrowError(new PairingError('FRAME_TAMPERED'));expect(()=>decryptFrame(k,{...f,version:0 as 1},'phone',0)).toThrowError(new PairingError('PROTOCOL_DOWNGRADE'));expect(()=>decryptFrame(k,{...f,senderId:'attacker'},'phone',0)).toThrowError(new PairingError('IDENTITY_MISMATCH'));});
 it('revokes old credentials',()=>{const r=new PairingRegistry();r.pair({host:{id:'host',publicKey:'h',pairedAt:1},phone:{id:'phone',publicKey:'p',pairedAt:1}});r.revoke('phone');expect(()=>r.assertUsable('phone')).toThrowError(new PairingError('REVOKED'));});
 it('restart/update persists and reinstall resets',async()=>{const s=store();const i=createIdentity('stable');await saveIdentity(s,i);expect((await loadIdentity(s))?.privateKey).toBe(i.privateKey);expect(await loadIdentity(store())).toBeNull();});
 it('does not expose invitation secret in encoded transport',()=>{const i=issueInvitation(createIdentity('host'));expect(encodeInvitation(i)).not.toContain(i.secret);});
});
