/* Browser Relay V2 wire catalog. Kept in sync with src/shared/contract/browserRelay.ts. */
globalThis.NEO_BROWSER_RELAY_V2 = Object.freeze({
  protocolVersion: '2.2',
  capabilities: Object.freeze([
    'lease.request',
    'lease.request.cancel',
    'lease.return',
    'operation.cancel',
    'tab.agent_window',
    'tab.navigate',
    'tab.screenshot',
    'dom.snapshot',
    'ax.snapshot',
    'network.metadata',
    'dialog.control',
    'file.upload',
    'input.mouse',
    'input.keyboard',
  ]),
  actionMethods: Object.freeze({
    navigate: 'tab.navigate',
    back: 'tab.back',
    forward: 'tab.forward',
    reload: 'tab.reload',
    click: 'input.click',
    click_text: 'input.click_text',
    type: 'input.type',
    press_key: 'input.key',
    scroll: 'input.scroll',
    hover: 'input.hover',
    drag: 'input.drag',
    get_dialog_state: 'dialog.get',
    handle_dialog: 'dialog.handle',
    upload_file: 'dom.set_file_input_files',
    screenshot: 'tab.screenshot',
    get_content: 'page.content',
    get_dom_snapshot: 'dom.snapshot',
    get_a11y_snapshot: 'ax.snapshot',
    get_workbench_state: 'lease.get',
    get_account_state: 'lease.get',
    wait: 'operation.wait',
    get_logs: 'page.logs',
  }),
});
