// ============================================================================
// PPT 模块常量 — 集中管理 PPT 生成模块的配置值
// ============================================================================
// 遵循 shared/constants.ts 的管理模式，PPT 模块内禁止散布魔法数字
// ============================================================================

// ---- 图表 ----

/** 图表数量级校验：最大值/最小值比超过此阈值则不适合同一图表 */
export const CHART_SCALE_MAX_RATIO = 1000;

/** 图表标签/数据最大切片数 */
export const CHART_MAX_ITEMS = 6;

/** 图表数据最少数据点数 */
export const CHART_MIN_DATA_POINTS = 3;

/** 图表标签前缀最大字符数（超过说明数字不是核心信息） */
export const CHART_LABEL_MAX_PREFIX = 15;

/** 图表标签截断长度 */
export const CHART_LABEL_MAX_LENGTH = 20;

// ---- 内容检测正则 ----

/** 数据相关关键词（标题必须含这些词才启用图表检测） */
export const DATA_KEYWORDS_PATTERN = /数据|统计|市场|规模|增长|趋势|占比|份额|对比|排名|指标|data|market|stats|growth/i;

/** 百分比/占比关键词 → 环形图 */
export const CHART_DOUGHNUT_PATTERN = /占比|比例|份额|分布|percent|share|ratio/i;

/** 时间序列关键词 → 折线图 */
export const CHART_LINE_PATTERN = /趋势|增长|变化|年|月|季度|trend|growth|timeline|year|month/i;

/** 排名/对比关键词 → 条形图 */
export const CHART_BAR_PATTERN = /排名|排行|对比|top|rank|compare/i;

/** 数字提取模式（含单位） */
export const NUMBER_WITH_UNIT_PATTERN = /\d+[\d.,]*[%万亿KMB]?/i;

/** 流程/步骤检测（仅标题） → timeline 布局 */
export const PROCESS_PATTERN = /流程|步骤|阶段|step|phase|stage/i;

/** 对比检测 → comparison 布局 */
export const COMPARISON_PATTERN = /对比|比较|vs|区别|优势|劣势|特点/i;

/** 重点检测（仅标题） → highlight 布局 */
export const KEY_POINT_PATTERN = /核心|关键|重点|最重要|价值|意义/i;

/** 技术检测（仅标题） → cards 布局 */
export const TECHNICAL_PATTERN = /架构|技术|实现|原理|算法|系统|模块/i;

/** 引用检测（仅标题 + 要点 ≤2） → quote 布局 */
export const QUOTE_PATTERN = /引言|语录|名言|格言|quote|saying/i;

// ---- 布局节奏 ----

/** 布局节奏控制配置 */
export const LAYOUT_RHYTHM = {
  /** 连续相同布局的最大次数 */
  MAX_CONSECUTIVE_SAME: 2,
  /** 连续 stats 布局的最大次数 */
  MAX_CONSECUTIVE_STATS: 1,
  /** 多样性检查的回溯窗口大小 */
  DIVERSITY_WINDOW: 5,
  /** 窗口内同一布局最大出现次数 */
  MAX_IN_WINDOW: 2,
} as const;

// ---- 幻灯片尺寸 ----

/** 标准 16:9 宽屏幻灯片尺寸（英寸） */
export const SLIDE = {
  WIDTH: 10,
  HEIGHT: 5.63,
} as const;

// ---- 设计模式画布 ----

/** Design Mode 脚手架画布常量（注入到 LLM 生成的脚本中） */
export const DESIGN_CANVAS = {
  WIDTH: 13.33,
  HEIGHT: 7.5,
  MARGIN_X: 0.7,
  MARGIN_Y: 0.5,
} as const;

// ---- 文本度量 ----

/** 字符宽度估算因子（英寸/点） — 用于 calculateFitFontSize */
export const TEXT_METRICS = {
  /** CJK 字符宽度因子（近似方形） */
  CJK_WIDTH_FACTOR: 0.035,
  /** Latin 字符宽度因子（较窄） */
  LATIN_WIDTH_FACTOR: 0.02,
  /** 行高乘数 */
  LINE_HEIGHT_FACTOR: 1.3,
  /** CJK 主导判定阈值（CJK 字符占比 > 此值视为 CJK 主导） */
  CJK_DOMINANT_THRESHOLD: 0.3,
} as const;

// ---- 自适应字号 ----

/** 自适应字号阈值配置 */
export const ADAPTIVE_FONT = {
  /** 长文本阈值（等效字符数，超过则减 2pt） */
  LONG_TEXT_THRESHOLD: 80,
  /** 中等文本阈值（等效字符数，超过则减 1pt） */
  MEDIUM_TEXT_THRESHOLD: 50,
  /** 长文本字号减小量 (pt) */
  LONG_TEXT_REDUCTION: 2,
  /** 中等文本字号减小量 (pt) */
  MEDIUM_TEXT_REDUCTION: 1,
  /** 最小字号下限 (pt) */
  MIN_FONT_SIZE: 10,
} as const;

// ---- 设计模式 ----

/** Design Mode 执行配置 */
export const DESIGN_MODE = {
  /** VLM 审查最大修订轮数 */
  MAX_REVISIONS: 2,
  /** L2 降级时的简化页数上限 */
  SIMPLIFIED_SLIDE_COUNT: 8,
  /** 脚本执行超时 (ms) */
  SCRIPT_TIMEOUT: 30_000,
  /** tsx 执行输出缓冲区上限 (bytes) */
  MAX_BUFFER: 10 * 1024 * 1024,
} as const;

// ---- 外部工具超时 ----

/** PDF/图片转换工具超时 (ms) */
export const CONVERT_TIMEOUTS = {
  /** LibreOffice PPTX→PDF */
  PDF_CONVERT: 60_000,
  /** poppler pdftoppm */
  PDFTOPPM: 60_000,
  /** ImageMagick convert/magick */
  IMAGEMAGICK: 120_000,
  /** macOS qlmanage */
  QLMANAGE: 30_000,
} as const;

// ---- PDF 渲染参数 ----

/** PDF 转图片质量参数 */
export const PDF_RENDER = {
  /** JPEG 质量 (0-100) */
  QUALITY: 85,
  /** 渲染分辨率 (DPI) */
  DPI: 150,
  /** macOS qlmanage 缩略图尺寸 (px) */
  QLMANAGE_SIZE: 1920,
} as const;

// ---- 研究数据裁切 ----

/** 注入 Prompt 时研究数据的最大条数 */
export const RESEARCH_SLICE = {
  STATISTICS: 10,
  FACTS: 8,
  QUOTES: 3,
} as const;

// ---- VLM 审查 ----

/** VLM（视觉语言模型）请求超时 (ms) */
export const VLM_REQUEST_TIMEOUT = 60_000;

// ---- LibreOffice ----

/** LibreOffice 路径环境变量名 */
export const LIBREOFFICE_PATH_ENV = 'LIBREOFFICE_PATH';

/** LibreOffice 默认搜索路径（按优先级排序） */
export const LIBREOFFICE_SEARCH_PATHS = [
  '/Applications/LibreOffice.app/Contents/MacOS/soffice',
  '/usr/bin/libreoffice',
  '/usr/local/bin/libreoffice',
];

// ---- 预览 ----

/** 预览截断长度 */
export const PREVIEW_CODE_TRUNCATE = 200;

// ---- 默认回退值 ----

/** 主题缺失时的回退颜色（hex 无 #） */
export const DEFAULT_FALLBACK_COLORS = { background: 'ffffff', text: '000000', accent: '0071e3', secondary: '666666' } as const;

/** 主题缺失时的回退字体 */
export const DEFAULT_FALLBACK_FONTS = { title: 'Arial', body: 'Arial' } as const;

/** 代码块默认字体 */
export const DEFAULT_CODE_FONT = 'Consolas';

/** 结尾页默认标题 */
export const DEFAULT_END_TITLE = '谢谢观看';

/** 默认副标题 */
export const DEFAULT_SUBTITLE = '深度解析与实践指南';

// ---- 品牌文案 ----

export const BRAND_GENERATED_BY = 'GENERATED BY CODE AGENT';
export const BRAND_POWERED_BY = 'POWERED BY CODE AGENT';
export const BRAND_THANK_YOU = 'THANK YOU FOR YOUR ATTENTION';

// ---- 数据处理 ----

/** 概览页最大列数 */
export const DATA_OVERVIEW_MAX_COLUMNS = 6;

/** 详情页 Top-N 条目数 */
export const DATA_DETAIL_TOP_N = 5;

/** 详情页最大展示列数 */
export const DATA_DETAIL_MAX_DISPLAY_COLS = 4;

/** 图表默认最大数据项 */
export const CHART_DEFAULT_MAX_ITEMS = 8;

/** 数值格式化：亿阈值 */
export const FORMAT_YI_THRESHOLD = 1e8;

/** 数值格式化：万阈值 */
export const FORMAT_WAN_THRESHOLD = 1e4;

/** 数值列判定阈值（数值占比 > 此值视为数值列） */
export const NUMERIC_COLUMN_THRESHOLD = 0.5;

// ---- 密度控制 ----

/** 单页最大要点数 */
export const DENSITY_MAX_POINTS = 6;

/** 单页最少要点数 */
export const DENSITY_MIN_POINTS = 2;

// ---- 研究 Agent ----

/** 研究 Agent 默认目标要点数 */
export const DEFAULT_TARGET_POINT_COUNT = 4;

/** 默认幻灯片页数 */
export const DEFAULT_SLIDE_COUNT = 10;

/** 研究搜索最大查询数 */
export const RESEARCH_MAX_QUERIES = 5;

/** 研究搜索最大 URL 数 */
export const RESEARCH_MAX_URLS = 5;

/** 研究抓取最大页面数 */
export const RESEARCH_MAX_FETCH = 3;

/** 研究内容最大字符数 */
export const RESEARCH_MAX_CONTENT_CHARS = 8000;

// ---- 叙事验证 ----

/** 连续数值短语触发警告的阈值 */
export const NARRATIVE_NUMERIC_THRESHOLD = 3;

/** 连续数据幻灯片最大数 */
export const NARRATIVE_MAX_CONSECUTIVE_DATA = 3;

// ---- PowerPoint 单位 ----

/** EMU/英寸转换因子 */
export const EMU_PER_INCH = 914400;

// ---- Master 布局共享位置 ----

/** 内容页标题位置（英寸） */
export const MASTER_CONTENT_TITLE = { x: 0.7, y: 0.28, w: 8, h: 0.95 } as const;

/** 内容页标题字号 */
export const MASTER_CONTENT_TITLE_FONT = { apple: 32, default: 30 } as const;

/** 页脚左侧位置 */
export const MASTER_FOOTER_LEFT = { x: 0.5, y: 5.15, w: 4, h: 0.25, fontSize: 9 } as const;

/** 页脚右侧位置 */
export const MASTER_FOOTER_RIGHT = { x: 7.5, y: 5.15, w: 2, h: 0.25, fontSize: 9 } as const;

// ---- 装饰共享元素 ----

/** Apple 主题强调条 */
export const APPLE_ACCENT_BAR = { x: 0.4, y: 0.4, w: 0.06, h: 0.65, transparency: 0 } as const;

/** Apple 主题内容面板 */
export const APPLE_CONTENT_PANEL = { x: 0.4, y: 1.35, w: 9.2, h: 4.0, radius: 0.2 } as const;

/** 默认主题强调条 */
export const DEFAULT_ACCENT_BAR = { x: 0.4, y: 0.4, w: 0.15, h: 0.65, transparency: 0 } as const;

/** 默认主题内容面板 */
export const DEFAULT_CONTENT_PANEL = { x: 0.4, y: 1.35, w: 9.2, h: 4.0, radius: 0.2 } as const;

/** 卡片默认圆角 */
export const DEFAULT_CARD_RADIUS = 0.2;

/** 默认装饰预算 */
export const DECORATION_BUDGET_DEFAULT = { maxGlows: 3, maxLines: 4, maxPanels: 2, maxTotal: 7 } as const;

/** 标题页装饰预算 */
export const DECORATION_BUDGET_TITLE = { maxGlows: 3, maxLines: 4, maxPanels: 2, maxTotal: 8 } as const;
