// ============================================================================
// PPT Generate Tool - 模块化入口
// 支持 Slide Master 声明式设计 + 原生可编辑图表 + apple-dark 主题
// ============================================================================

import type { Tool, ToolContext, ToolExecutionResult } from '../../toolRegistry';
import * as fs from 'fs';
import * as path from 'path';
import type { PPTGenerateParams, SlideImage, ChartMode } from './types';
import { getThemeConfig } from './themes';
import { parseContentToSlides, generatePlaceholderSlides } from './parser';
import { registerSlideMasters } from './slideMasters';
import { selectMasterAndLayout, fillSlide, resetLayoutRotation } from './layouts';
import { formatFileSize } from '../utils';


// Use require for pptxgenjs (CJS compatible with Electron)
function getPptxGenJS() {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const PptxGenJS = require('pptxgenjs');
  return PptxGenJS;
}

export const pptGenerateTool: Tool = {
  name: 'ppt_generate',
  description: `生成 2026 设计标准的 PowerPoint 演示文稿。

**设计特点：**
- Slide Master 声明式设计（可编辑模板）
- 原生可编辑图表（自动检测数据内容）
- Bento Grid 模块化布局
- 深色 + 霓虹强调色配色
- 超大字体标题

**9 种配色主题：**
- neon-green: 深黑 + 荧光绿（科技感，推荐）
- neon-blue: 深黑 + 电光蓝（专业感）
- neon-purple: 深紫 + 霓虹紫（创意感）
- neon-orange: 深灰 + 霓虹橙（活力感）
- glass-light: 浅色玻璃态（简约感）
- glass-dark: 深色玻璃态（高端感）
- minimal-mono: 纯黑白（极简感）
- corporate: 企业蓝（商务感）
- apple-dark: 苹果发布会极简风格（纯黑 + 苹果蓝）

**内容格式（Markdown）：**
\`\`\`
# 标题页
## 副标题

# 第一章
- 要点 1
- 要点 2
- 要点 3
- 要点 4

# 谢谢观看
\`\`\`

**重要提示：**
- 每张幻灯片 4-5 个要点，每个要点 20-40 字
- 内容必须具体，包含数据和事实
- 包含数字的要点会自动生成原生可编辑图表
- 支持 Mermaid 图表自动渲染`,
  generations: ['gen3', 'gen4', 'gen5', 'gen6', 'gen7', 'gen8'],
  requiresPermission: true,
  permissionLevel: 'write',
  inputSchema: {
    type: 'object',
    properties: {
      topic: {
        type: 'string',
        description: '演示文稿的主题/标题',
      },
      content: {
        type: 'string',
        description: '详细内容大纲（Markdown 格式）',
      },
      slides_count: {
        type: 'number',
        description: '幻灯片数量（默认: 6）',
        default: 6,
      },
      theme: {
        type: 'string',
        enum: [
          'neon-green', 'neon-blue', 'neon-purple', 'neon-orange',
          'glass-light', 'glass-dark', 'minimal-mono', 'corporate',
          'apple-dark',
        ],
        description: '配色主题（默认: neon-green）',
        default: 'neon-green',
      },
      output_path: {
        type: 'string',
        description: '输出文件路径',
      },
      images: {
        type: 'array',
        description: '要嵌入的图片列表',
        items: {
          type: 'object',
          properties: {
            slide_index: { type: 'number', description: '幻灯片索引（从 0 开始）' },
            image_path: { type: 'string', description: '图片文件路径' },
            position: { type: 'string', enum: ['right', 'left', 'center', 'background', 'bento'] },
          },
          required: ['slide_index', 'image_path'],
        },
      },
      use_masters: {
        type: 'boolean',
        description: '使用 Slide Master 模式（默认: true）',
        default: true,
      },
      chart_mode: {
        type: 'string',
        enum: ['auto', 'none'],
        description: '图表模式：auto 自动检测数据生成原生图表，none 不生成图表（默认: auto）',
        default: 'auto',
      },
    },
    required: ['topic'],
  },

  async execute(
    params: Record<string, unknown>,
    context: ToolContext
  ): Promise<ToolExecutionResult> {
    const {
      topic,
      content,
      slides_count = 6,
      theme = 'neon-green',
      output_path,
      images = [],
      chart_mode = 'auto',
    } = params as unknown as PPTGenerateParams;

    try {
      const Pptx = getPptxGenJS();
      const timestamp = Date.now();
      const fileName = `presentation-${timestamp}.pptx`;
      const outputDir = output_path ? path.dirname(output_path) : context.workingDirectory;
      const finalPath = output_path || path.join(outputDir, fileName);

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      const pptx = new Pptx();
      const themeConfig = getThemeConfig(theme as string);

      pptx.author = 'Code Agent';
      pptx.title = topic;
      pptx.subject = topic;
      pptx.company = 'Generated by Code Agent';

      // 解析内容
      const processedContent = content || '';
      const slideImages = (images as SlideImage[]) || [];

      const slides = processedContent
        ? parseContentToSlides(processedContent, slides_count)
        : generatePlaceholderSlides(topic, slides_count);

      // Slide Master + 声明式填充
      registerSlideMasters(pptx, themeConfig);
      resetLayoutRotation();

      for (let i = 0; i < slides.length; i++) {
        const slideData = slides[i];

        const currentSlideImages = slideImages?.filter(
          img => img.slide_index === i && fs.existsSync(img.image_path)
        ) || [];

        const { master, layout, chartData } = selectMasterAndLayout(
          slideData,
          currentSlideImages.length > 0,
          chart_mode as ChartMode
        );

        const slide = pptx.addSlide({ masterName: master });
        fillSlide(pptx, slide, slideData, themeConfig, layout, i, chartData, currentSlideImages);
      }

      await pptx.writeFile({ fileName: finalPath });
      const stats = fs.statSync(finalPath);

      const chartInfo = chart_mode === 'auto' ? '，原生图表自动检测' : '';

      return {
        success: true,
        output: `PPT 已生成（Slide Master 模式${chartInfo}）

文件: ${finalPath}
主题: ${themeConfig.name} (${theme})
幻灯片: ${slides.length} 页
大小: ${formatFileSize(stats.size)}

点击文件路径可直接打开。`,
        metadata: {
          filePath: finalPath,
          fileName: path.basename(finalPath),
          fileSize: stats.size,
          slidesCount: slides.length,
          theme,
          chartMode: chart_mode,
          attachment: {
            id: `ppt-${timestamp}`,
            type: 'file',
            category: 'document',
            name: path.basename(finalPath),
            path: finalPath,
            size: stats.size,
            mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        error: `PPT 生成失败: ${error.message}`,
      };
    }
  },
};
