// ============================================================================
// PPT Slide Master 定义 - 声明式设计
// 使用 pptx.defineSlideMaster() 创建可复用的幻灯片模板
// ============================================================================

import type { ThemeConfig } from './types';
import { isAppleDark } from './themes';

// Master 名称常量
export const MASTER = {
  TITLE: 'MASTER_TITLE',
  CONTENT_LIST: 'MASTER_CONTENT_LIST',
  CONTENT_CHART: 'MASTER_CONTENT_CHART',
  CONTENT_IMAGE: 'MASTER_CONTENT_IMAGE',
  END: 'MASTER_END',
  HERO_NUMBER: 'MASTER_HERO_NUMBER',
} as const;

/**
 * 注册所有 Slide Master 到 pptx 实例
 */
export function registerSlideMasters(pptx: any, theme: ThemeConfig): void {
  const apple = isAppleDark(theme);

  registerTitleMaster(pptx, theme, apple);
  registerContentListMaster(pptx, theme, apple);
  registerContentChartMaster(pptx, theme, apple);
  registerContentImageMaster(pptx, theme, apple);
  registerEndMaster(pptx, theme, apple);
  registerHeroNumberMaster(pptx, theme, apple);
}

// ============================================================================
// TITLE Master - 封面页
// ============================================================================
function registerTitleMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  if (!apple) {
    // 右上角渐变圆环
    objects.push({
      ellipse: { x: 6, y: -1.5, w: 5, h: 5, fill: { color: theme.accent, transparency: 95 } },
    });
    objects.push({
      ellipse: { x: 6.5, y: -1, w: 4, h: 4, fill: { color: theme.bgColor } },
    });
    // 左下角光晕
    objects.push({
      ellipse: { x: -2, y: 4, w: 6, h: 6, fill: { color: theme.accent, transparency: 97 } },
    });
    // 竖线装饰
    objects.push({
      rect: { x: 8.5, y: 1.2, w: 0.02, h: 2, fill: { color: theme.accent, transparency: 60 } },
    });
    objects.push({
      rect: { x: 9, y: 0.8, w: 0.02, h: 2.8, fill: { color: theme.accent, transparency: 40 } },
    });
  }

  // 左侧强调竖条（所有主题通用）
  objects.push({
    rect: { x: 0.4, y: 2, w: apple ? 0.06 : 0.12, h: 1.8, fill: { color: theme.accent } },
  });

  if (!apple) {
    // 竖条端点圆点
    objects.push({
      ellipse: { x: 0.38, y: 1.9, w: 0.16, h: 0.16, fill: { color: theme.accent } },
    });
    objects.push({
      ellipse: { x: 0.38, y: 3.74, w: 0.16, h: 0.16, fill: { color: theme.accent } },
    });
  }

  // 标题下方强调线
  objects.push({
    rect: { x: 0.8, y: 3.4, w: 3, h: apple ? 0.03 : 0.06, fill: { color: theme.accent } },
  });
  if (!apple) {
    objects.push({
      rect: { x: 3.8, y: 3.4, w: 1.5, h: 0.06, fill: { color: theme.accent, transparency: 50 } },
    });
    objects.push({
      rect: { x: 5.3, y: 3.4, w: 1, h: 0.06, fill: { color: theme.accent, transparency: 80 } },
    });
  }

  // 底部分隔线
  objects.push({
    rect: { x: 0.5, y: 5, w: 9, h: 0.01, fill: { color: theme.cardBorder } },
  });

  // 底部信息
  objects.push({
    text: {
      text: 'GENERATED BY CODE AGENT',
      options: { x: 0.5, y: 5.15, w: 4, h: 0.25, fontSize: 9, fontFace: theme.fontBody, color: theme.textSecondary, charSpacing: 3 },
    },
  });

  // 日期
  const date = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: '2-digit' });
  objects.push({
    text: {
      text: date,
      options: { x: 7.5, y: 5.15, w: 2, h: 0.25, fontSize: 9, fontFace: theme.fontBody, color: theme.textSecondary, align: 'right' },
    },
  });

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 0.8,
        y: 1.9,
        w: 7.5,
        h: 1.4,
        fontSize: apple ? 56 : 64,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
        valign: 'middle',
      },
    },
  });

  // Placeholder: 副标题（body）
  objects.push({
    placeholder: {
      options: {
        name: 'body',
        type: 'body',
        x: 0.8,
        y: 3.65,
        w: 8,
        h: 0.6,
        fontSize: apple ? 18 : 22,
        fontFace: theme.fontBody,
        color: theme.textSecondary,
        charSpacing: apple ? 1 : 2,
      },
    },
  });

  pptx.defineSlideMaster({
    title: MASTER.TITLE,
    background: { color: theme.bgColor },
    objects,
  });
}

// ============================================================================
// CONTENT_LIST Master - 内容列表页
// ============================================================================
function registerContentListMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  // 标题左侧强调块
  objects.push({
    rect: { x: 0.4, y: 0.45, w: apple ? 0.06 : 0.15, h: 0.6, fill: { color: theme.accent }, rectRadius: 0.03 },
  });

  // 标题下方装饰线
  objects.push({
    rect: { x: 0.7, y: 1.15, w: 2, h: 0.03, fill: { color: theme.accent } },
  });
  if (!apple) {
    objects.push({
      rect: { x: 2.7, y: 1.15, w: 1, h: 0.03, fill: { color: theme.accent, transparency: 60 } },
    });
  }

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 0.7,
        y: 0.35,
        w: 8,
        h: 0.8,
        fontSize: apple ? 28 : 32,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
      },
    },
  });

  // Placeholder: body（内容区域）
  objects.push({
    placeholder: {
      options: {
        name: 'body',
        type: 'body',
        x: 0.5,
        y: 1.4,
        w: 9,
        h: 3.8,
        fontSize: apple ? 16 : 14,
        fontFace: theme.fontBody,
        color: theme.textSecondary,
        valign: 'top',
        bullet: true,
      },
    },
  });

  pptx.defineSlideMaster({
    title: MASTER.CONTENT_LIST,
    background: { color: theme.bgColor },
    objects,
  });
}

// ============================================================================
// CONTENT_CHART Master - 左文右图表页
// ============================================================================
function registerContentChartMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  // 标题左侧强调块
  objects.push({
    rect: { x: 0.4, y: 0.45, w: apple ? 0.06 : 0.15, h: 0.6, fill: { color: theme.accent }, rectRadius: 0.03 },
  });

  // 标题下方装饰线
  objects.push({
    rect: { x: 0.7, y: 1.15, w: 2, h: 0.03, fill: { color: theme.accent } },
  });

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 0.7,
        y: 0.35,
        w: 8,
        h: 0.8,
        fontSize: apple ? 28 : 32,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
      },
    },
  });

  // Placeholder: 左侧 body（文字要点）
  objects.push({
    placeholder: {
      options: {
        name: 'body',
        type: 'body',
        x: 0.5,
        y: 1.4,
        w: 4.3,
        h: 3.8,
        fontSize: apple ? 14 : 13,
        fontFace: theme.fontBody,
        color: theme.textSecondary,
        valign: 'top',
        bullet: true,
      },
    },
  });

  // 注意：图表区域（右侧 5.1, 1.4, 4.5, 3.8）由 layouts.ts 中用 addChart() 填充

  pptx.defineSlideMaster({
    title: MASTER.CONTENT_CHART,
    background: { color: theme.bgColor },
    objects,
  });
}

// ============================================================================
// CONTENT_IMAGE Master - 左文右图片页
// ============================================================================
function registerContentImageMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  // 标题左侧强调块
  objects.push({
    rect: { x: 0.4, y: 0.5, w: apple ? 0.06 : 0.08, h: 0.5, fill: { color: theme.accent } },
  });

  // 标题下方装饰线
  objects.push({
    rect: { x: 0.6, y: 1.05, w: 1.5, h: 0.03, fill: { color: theme.accent } },
  });

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 0.6,
        y: 0.35,
        w: 8,
        h: 0.8,
        fontSize: apple ? 24 : 28,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
      },
    },
  });

  // Placeholder: 左侧 body
  objects.push({
    placeholder: {
      options: {
        name: 'body',
        type: 'body',
        x: 0.5,
        y: 1.4,
        w: 4.3,
        h: 3.6,
        fontSize: 12,
        fontFace: theme.fontBody,
        color: theme.textSecondary,
        valign: 'top',
        bullet: true,
      },
    },
  });

  // 右侧图片容器背景
  if (!apple) {
    objects.push({
      rect: {
        x: 4.9,
        y: 1.2,
        w: 4.8,
        h: 4.0,
        fill: { color: theme.bgSecondary },
        line: { color: theme.cardBorder, width: 0.5 },
        rectRadius: 0.1,
      },
    });
  }

  pptx.defineSlideMaster({
    title: MASTER.CONTENT_IMAGE,
    background: { color: theme.bgColor },
    objects,
  });
}

// ============================================================================
// END Master - 结束页
// ============================================================================
function registerEndMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  if (!apple) {
    // 大型渐变圆环
    objects.push({
      ellipse: { x: 4.5, y: 1, w: 6, h: 6, fill: { color: theme.accent, transparency: 96 } },
    });
    objects.push({
      ellipse: { x: 5, y: 1.5, w: 5, h: 5, fill: { color: theme.bgColor } },
    });
    // 装饰线条
    objects.push({
      rect: { x: 7.5, y: 0.5, w: 2, h: 0.015, fill: { color: theme.cardBorder } },
    });
    objects.push({
      rect: { x: 8, y: 0.7, w: 1.5, h: 0.015, fill: { color: theme.cardBorder, transparency: 50 } },
    });
    // 几何装饰
    objects.push({
      rect: { x: 0.3, y: 4.5, w: 1.2, h: 1.2, fill: { color: theme.accent, transparency: 95 }, rectRadius: 0.15 },
    });
  }

  // 主内容卡片（apple 不要卡片边框）
  if (!apple) {
    objects.push({
      rect: { x: 1.5, y: 1.8, w: 7, h: 2.6, fill: { color: theme.bgSecondary }, line: { color: theme.cardBorder, width: 0.5 }, rectRadius: 0.2 },
    });
    // 卡片顶部强调线
    objects.push({
      rect: { x: 4, y: 1.8, w: 2, h: 0.06, fill: { color: theme.accent } },
    });
  } else {
    // apple: 只有细横线
    objects.push({
      rect: { x: 3.5, y: 3.3, w: 3, h: 0.02, fill: { color: theme.accent } },
    });
  }

  // 装饰分隔线（非 apple）
  if (!apple) {
    objects.push({
      rect: { x: 3.5, y: 3.3, w: 3, h: 0.03, fill: { color: theme.accent } },
    });
    objects.push({
      rect: { x: 3, y: 3.3, w: 0.4, h: 0.03, fill: { color: theme.accent, transparency: 50 } },
    });
    objects.push({
      rect: { x: 6.6, y: 3.3, w: 0.4, h: 0.03, fill: { color: theme.accent, transparency: 50 } },
    });
  }

  // 副文案
  objects.push({
    text: {
      text: 'THANK YOU FOR YOUR ATTENTION',
      options: {
        x: 1.5, y: 3.6, w: 7, h: 0.4,
        fontSize: apple ? 10 : 12, fontFace: theme.fontBody,
        color: theme.textSecondary, charSpacing: apple ? 6 : 4, align: 'center',
      },
    },
  });

  // 底部信息栏
  objects.push({
    rect: { x: 0.5, y: 5, w: 9, h: 0.01, fill: { color: theme.cardBorder } },
  });
  objects.push({
    text: {
      text: 'POWERED BY CODE AGENT',
      options: { x: 0.5, y: 5.15, w: 4, h: 0.25, fontSize: 9, fontFace: theme.fontBody, color: theme.textSecondary, charSpacing: 2 },
    },
  });
  const date = new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: '2-digit' });
  objects.push({
    text: {
      text: date,
      options: { x: 7.5, y: 5.15, w: 2, h: 0.25, fontSize: 9, fontFace: theme.fontBody, color: theme.textSecondary, align: 'right' },
    },
  });

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 1.5,
        y: 2.2,
        w: 7,
        h: 1,
        fontSize: apple ? 42 : 48,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
        align: 'center',
      },
    },
  });

  pptx.defineSlideMaster({
    title: MASTER.END,
    background: { color: theme.bgColor },
    objects,
  });
}

// ============================================================================
// HERO_NUMBER Master - 大数字展示页（apple 风格）
// ============================================================================
function registerHeroNumberMaster(pptx: any, theme: ThemeConfig, apple: boolean) {
  const objects: any[] = [];

  // 标题左侧强调块
  objects.push({
    rect: { x: 0.4, y: 0.45, w: apple ? 0.06 : 0.15, h: 0.6, fill: { color: theme.accent }, rectRadius: 0.03 },
  });

  // 标题下方装饰线
  objects.push({
    rect: { x: 0.7, y: 1.15, w: 2, h: 0.03, fill: { color: theme.accent } },
  });

  // Placeholder: 标题
  objects.push({
    placeholder: {
      options: {
        name: 'slideTitle',
        type: 'title',
        x: 0.7,
        y: 0.35,
        w: 8,
        h: 0.8,
        fontSize: apple ? 28 : 32,
        fontFace: theme.fontTitle,
        color: theme.textPrimary,
        bold: true,
      },
    },
  });

  // 注意：HERO_NUMBER 不定义 body placeholder
  // stats/cards/timeline 布局用坐标填充内容，body placeholder 会留空显示 "Click to add text"

  pptx.defineSlideMaster({
    title: MASTER.HERO_NUMBER,
    background: { color: theme.bgColor },
    objects,
  });
}
