// AUTO-GENERATED by scripts/generate-game-skill-content.mjs - do not edit by hand.
// Regenerate: node scripts/generate-game-skill-content.mjs

export const GAME_SKILL_GENERATION_CONTRACT: Record<string, string> = {
  "platformer": `> This section is build-time inlined into game prompt assembly so the SKILL.md
> stays a single-source-of-truth reference for platformer generation guidance.

- Translate genre/reference into mechanics, not only visual skin.
- Platformers must include acceleration/friction, gravity, jump buffering or coyote
  time, recovery, and input-driven collision with platforms, hazards, rewards, and goals.
- Gameplay Mechanics Contract: implement a stompable enemy, a bumpable/question block,
  a movement/interaction-changing ability, an ability-gated route, and one
  comboChallenge that combines jump with at least two of enemy/block/ability/gate play.
- For subtype \`platformer\`, use exact shape
  \`gameplayMechanics: { enemies: [], blocks: [], abilities: [], gates: [], comboChallenge: [] }\`;
  each field is an array even when it has one item, never an object map.
- Fill \`stompable\`/\`defeatReward\`, \`bumpableFromBelow\`/\`reward\`/\`usedState\`,
  \`acquiredFrom\`/\`effect\`/\`unlocksRoute\`, \`requiresAbility\`/\`blocksAccessTo\`,
  \`requires\`/\`target\`. Use \`doubleJump\`, \`dash\`, \`shield\`, \`magnet\`, \`groundPound\`,
  or \`wallJump\`.
- For movement metrics like \`player.x\`, \`player.y\`, \`player.vx\`, \`player.vy\`, the
  \`expect\` MUST be one of \`"increase"\` / \`"decrease"\` / \`"change"\`, never a numeric
  target. A numeric or boolean expect means exact final equality after the declared
  frames, only valid for counters like \`enemiesDefeated\` / \`blocksUsed\` /
  \`gatesUnlocked\` or boolean flags like \`abilities.doubleJump\`.
- Reachability steps must be short, deterministic, and locally true: use real snapshot
  paths such as \`player.x\`, \`player.vy\`, \`enemiesDefeated\`, \`blocksUsed\`,
  \`abilities.doubleJump\`, \`gatesUnlocked\`, \`routesUnlocked\`; do not expect
  score/progress/win/gate/ability changes unless that exact input window triggers
  live collision.
- For platformers, nearby authored smoke scenarios like \`reset('stomp')\`,
  \`reset('bumpBlock')\`, \`reset('gainAbility')\`, and \`reset('unlockGate')\` are better
  than long full-level treks, but they must still use live physics/collision.
- For platformers, \`runSmokeTest()\` proves gameplayMechanics with before/after
  snapshots: stomp enemy defeated plus player bounce/vy, bump block
  used/spawnedReward, ability changes, gate/route reachability after ability, and
  comboChallenge sequence.`,
  "runner": `- Player auto-moves along \`forwardAxis\` ("x" for horizontal runner, "y" for
  vertical). No left/right input drives forward motion.
- Controls: \`jump = Space\`, \`slide = ArrowDown\`. Optional: \`laneLeft = ArrowLeft\`,
  \`laneRight = ArrowRight\`.
- \`__GAME_META__\` shape:
  - \`subtype: 'runner'\`
  - \`autoRun: true\`
  - \`forwardAxis: 'x'\` (or \`'y'\`)
  - \`runSpeed: <number>\` (units per frame; integrate every step)
  - \`obstacles: [{ id, type, position, action }]\` — each entry mandatory
  - \`pickups: [{ id, type, position, value }]\` — optional but recommended
- \`snapshot()\` MUST expose: \`{ player: { x, y, vy }, distanceTraveled,
  obstaclesAvoided, pickupsCollected, gameOver, score, status }\`.
- \`progressPlan\` example:
  \`\`\`json
  [
    { "label": "auto-run", "input": "", "frames": 24, "metric": "distanceTraveled", "expect": "increase" },
    { "label": "jump dodge", "input": "Space", "frames": 12, "metric": "obstaclesAvoided", "expect": "increase" },
    { "label": "slide dodge", "input": "ArrowDown", "frames": 12, "metric": "obstaclesAvoided", "expect": "increase" }
  ]
  \`\`\`
- For movement metrics like \`player.x\`, \`distanceTraveled\`, \`obstaclesAvoided\`,
  \`pickupsCollected\`, \`expect\` MUST be one of \`"increase"\` / \`"decrease"\` /
  \`"change"\`, never a numeric target. Boolean expects (e.g. \`gameOver: true\`)
  are valid for terminal flags.

### Empty input for auto-run mechanics

Runner is the first genre with **legitimate empty / "none" input** in
\`progressPlan\`. The platformer validator currently rejects this because
platformer forward motion comes from ArrowRight presses; runner forward motion
comes from the time-step itself.

When generating a runner, declare the auto-run probe with \`input: ""\` (empty
string) — the validator should accept it for runner subtype because
\`autoRun: true\` in metadata makes forward motion implicit. If the validator
infrastructure rejects empty inputs uniformly, that's a gap to surface — runner
needs the validator to consult \`subtype\` before enforcing the "input must come
from controls" rule. **Do not** work around it by emitting bogus inputs like
\`"ArrowRight"\` for a game that ignores ArrowRight; that masks the architectural
gap and produces fake evidence.

### Smoke test contract

\`runSmokeTest()\` must drive \`step()\` and prove:

1. **Auto-run**: \`step("", 24)\` → assert \`after.distanceTraveled > before.distanceTraveled\`.
2. **Obstacle dodge**: \`step("Space", 12)\` over a jump-action obstacle → assert
   \`after.obstaclesAvoided > before.obstaclesAvoided\`.
3. **Pickup collect** (if pickups declared): \`step("", N)\` past a pickup
   → assert \`after.pickupsCollected > before.pickupsCollected\`.
4. **Death** (optional): drive into an unhandled obstacle → assert
   \`after.gameOver === true\`.

Coverage names returned by \`runSmokeTest().coverage\`:
\`coverage.mechanics = ["autoRun", "dodgeJump", "dodgeSlide", "collect"]\`,
\`coverage.stateChanges = ["distanceTraveled", "obstaclesAvoided", "pickupsCollected", "gameOver"]\`.`,
};

export const GAME_SKILL_REPAIR_HINTS: Record<string, string> = {
  "platformer": `| Failure Code | Hint |
|--------------|------|
| \`missing_gameplay_mechanics\` | Add \`gameplayMechanics\` to \`__GAME_META__\` with \`enemies\`, \`blocks\`, \`abilities\`, \`gates\`, \`comboChallenge\` (each an array, never a map). Implement collision: stomp marks enemy defeated and bounces \`player.vy\`; bump marks block used and spawns the ability; ability changes movement; gate checks ability before route access. |
| \`gameplay_mechanics_without_runtime_evidence\` | Repair \`runSmokeTest()\` so it drives \`step()\` through stomp enemy, bump block, gain ability, unlock gate/route, and combo challenge — record coverage only after before/after snapshot changes prove each mechanic. |
| \`ability_gate_without_reachability\` | Make one ability change movement or interaction rules and unlock a real gated route. \`snapshot()\` should expose \`abilities\` and gate/route state, and \`runSmokeTest()\` must prove ability \`false → true\` followed by gate/route \`unreachable → reachable\`. |

Other platformer-specific repair hints:

- For platformers, add/repair \`gameplayMechanics\` with enemies, blocks, abilities,
  gates, and comboChallenge, wired to real \`step()\` gameplay and \`runSmokeTest()\`
  before/after snapshot evidence.
- Platformer \`gameplayMechanics.enemies\`, \`blocks\`, \`abilities\`, \`gates\`, and
  \`comboChallenge\` must be arrays; do not repair them as \`{ enemies: { ... } }\` or
  keyed object maps.
- If the full level path is too long, repair platformers with deterministic authored
  scenarios for stomp, bumpBlock, gainAbility, unlockGate, and comboChallenge using
  the live rules.
- Platformer coverage must prove \`stompEnemy\`, \`bumpBlock\`, \`gainAbility\`,
  \`unlockGate\`/\`routeReachableAfterAbility\`, and \`comboChallenge\`, with stateChanges
  for \`enemiesDefeated\`, \`player.vy\`/bounce, \`blocksUsed\`/\`spawnedReward\`,
  \`abilities\`, and \`gates\`/\`routes\`.`,
  "runner": `| Failure Code | Hint |
|--------------|------|
| \`missing_runner_loop_metadata\` | Declare \`__GAME_META__.autoRun = true\` plus \`forwardAxis\` ("x" or "y") and \`runSpeed\`. \`step()\` must increment \`distanceTraveled\` even with empty input — forward motion is implicit from the time-step. |
| \`missing_obstacle_metadata\` | Add \`__GAME_META__.obstacles = [{ id, type, position, action }]\` with at least one entry. The \`action\` field tells the player how to dodge (jump / slide / swap-lane). Hitting an unhandled obstacle should set \`gameOver: true\`. |
| \`runner_no_distance_progression\` | Make \`step()\` unconditionally advance \`distanceTraveled\` by \`runSpeed * frames\` (or per-frame integration) regardless of input. \`runSmokeTest()\` must take a before snapshot, call \`step("", N)\` with empty input, take an after snapshot, and assert \`after.distanceTraveled > before.distanceTraveled\`. |

Other runner-specific repair hints:

- If your engine ties forward motion to keyboard handling (e.g. ArrowRight
  increments \`player.x\`), refactor: forward speed should come from a \`runSpeed\`
  constant integrated each frame, not from input handling. Input should only
  control jump / slide / lane.
- If smoke says "distance not increasing", the most common cause is that
  \`step()\` early-returns on empty input. Remove that guard.
- If \`obstaclesAvoided\` doesn't increment, check that the obstacle's \`action\`
  field matches the input you're driving (Space for jump, ArrowDown for slide).`,
};
