// AUTO-GENERATED by scripts/generate-game-skill-content.mjs - do not edit by hand.
// Regenerate: node scripts/generate-game-skill-content.mjs

export const GAME_SKILL_GENERATION_CONTRACT: Record<string, string> = {
  "breakout": `> This section is build-time inlined into game prompt assembly so the SKILL.md
> stays a single-source-of-truth reference for breakout generation guidance.

- Translate genre/reference into mechanics, not only visual skin.
- Breakout artifacts must expose \`__GAME_META__\` with \`subtype: 'breakout'\`
  or an arkanoid-compatible subtype/genre/type value.
- Implement a playable first screen on initial page load. Before any
  \`__GAME_TEST__\` helper mutates state, \`snapshot()\` must already expose
  \`brickCount\`, \`bricksRemaining\`, or \`bricks.length\` greater than 0.
- Wire real browser keyboard input. A real Space keypress from the initial
  loaded start state must launch the ball and change \`ball.x\` or \`ball.y\`.
  Do not depend on \`__GAME_TEST__.start()\` or \`reset('launch')\` pre-setting an
  already launched ball.
- \`snapshot()\` must expose paddle movement and ball motion state:
  \`paddleX\` or \`paddle.x\`; \`ball.x\`, \`ball.y\`, and at least one of \`ball.vx\`,
  \`ball.vy\`, \`ball.dx\`, \`ball.dy\`, or \`ball.speed\`.
- Wall and paddle bounces need explicit runtime counters:
  \`wallBounceCount\` and \`paddleBounceCount\`.
- Brick collision must produce a visible snapshot delta: \`brickCount\` or
  \`bricksRemaining\` decreases, and \`score\` increases.
- Author deterministic reset scenarios with these exact quoted ids:
  \`reset('paddleMove')\`, \`reset('launch')\`, \`reset('wallBounce')\`,
  \`reset('paddleBounce')\`, \`reset('brickHit')\`, \`reset('win')\`, and
  \`reset('lose')\`.
- Runtime evidence should report \`breakoutScenarios\` probes with
  \`{ name, before, after }\` for every deterministic scenario. Each probe must
  be driven by live \`step()\`/physics, not by directly editing the after
  snapshot.
- Add a real-browser initial launch probe named \`browserLaunchFromInitialLoad\`
  or \`browserLaunchFromStart\`. Its \`before\` snapshot needs initial bricks and
  its \`after\` snapshot needs changed ball coordinates after a browser Space
  key event.
- Required powerups and reset scenarios:
  - \`reset('powerup:wide')\`: triggers \`wide\`; \`paddle.width\` or \`paddleWidth\`
    increases, or the after snapshot records the \`wide\` powerup.
  - \`reset('powerup:multi')\`: triggers \`multi\`; \`ballCount\` or \`balls.length\`
    increases, or the after snapshot records the \`multi\` powerup.
  - \`reset('powerup:slow')\`: triggers \`slow\`; \`ball.speed\`, \`ballSpeed\`, or
    \`speed\` decreases, or the after snapshot records the \`slow\` powerup.
  - \`reset('powerup:through')\`: triggers \`through\`; \`through\`,
    \`ball.through\`, \`throughActive\`, \`powerups.through\`, or
    \`activePowerups.through\` becomes truthy, or the after snapshot records the
    \`through\` powerup.
  - \`reset('powerup:life')\`: triggers \`life\`; \`lives\`, \`player.lives\`, or
    \`state.lives\` increases, or the after snapshot records the \`life\` powerup.
- Win evidence should make \`status\` match \`won\`, \`win\`, \`complete\`, or
  \`cleared\`; lose evidence should make \`status\` match \`lost\`, \`lose\`,
  \`failed\`, or \`gameover\`, or reduce lives to 0.
- Start the live game loop with \`requestAnimationFrame(loop)\` or an equivalent
  browser loop before the script exits, and keep the canvas/game root focusable
  so keyboard events reach the live controls.`,
  "platformer": `> This section is build-time inlined into game prompt assembly so the SKILL.md
> stays a single-source-of-truth reference for platformer generation guidance.

- Translate genre/reference into mechanics, not only visual skin.
- Platformers must include acceleration/friction, gravity, jump buffering or coyote
  time, recovery, and input-driven collision with platforms, hazards, rewards, and goals.
- Gameplay Mechanics Contract: implement a stompable enemy, a bumpable/question block,
  a movement/interaction-changing ability, an ability-gated route, and one
  comboChallenge that combines jump with at least two of enemy/block/ability/gate play.
- For subtype \`platformer\`, use exact shape
  \`gameplayMechanics: { enemies: [], blocks: [], abilities: [], gates: [], comboChallenge: [] }\`;
  each field is an array even when it has one item, never an object map.
- Fill \`stompable\`/\`defeatReward\`, \`bumpableFromBelow\`/\`reward\`/\`usedState\`,
  \`acquiredFrom\`/\`effect\`/\`unlocksRoute\`, \`requiresAbility\`/\`blocksAccessTo\`,
  \`requires\`/\`target\`. Use \`doubleJump\`, \`dash\`, \`shield\`, \`magnet\`, \`groundPound\`,
  or \`wallJump\`.
- For movement metrics like \`player.x\`, \`player.y\`, \`player.vx\`, \`player.vy\`, the
  \`expect\` MUST be one of \`"increase"\` / \`"decrease"\` / \`"change"\`, never a numeric
  target. A numeric or boolean expect means exact final equality after the declared
  frames, only valid for counters like \`enemiesDefeated\` / \`blocksUsed\` /
  \`gatesUnlocked\` or boolean flags like \`abilities.doubleJump\`.
- Reachability steps must be short, deterministic, and locally true: use real snapshot
  paths such as \`player.x\`, \`player.vy\`, \`enemiesDefeated\`, \`blocksUsed\`,
  \`abilities.doubleJump\`, \`gatesUnlocked\`, \`routesUnlocked\`; do not expect
  score/progress/win/gate/ability changes unless that exact input window triggers
  live collision.
- For platformers, nearby authored smoke scenarios like \`reset('stomp')\`,
  \`reset('bumpBlock')\`, \`reset('gainAbility')\`, and \`reset('unlockGate')\` are better
  than long full-level treks, but they must still use live physics/collision.
- For platformers, \`runSmokeTest()\` proves gameplayMechanics with before/after
  snapshots: stomp enemy defeated plus player bounce/vy, bump block
  used/spawnedReward, ability changes, gate/route reachability after ability, and
  comboChallenge sequence.`,
  "runner": `- Player auto-moves along \`forwardAxis\` ("x" for horizontal runner, "y" for
  vertical). No left/right input drives forward motion.
- Controls: \`jump = Space\`, \`slide = ArrowDown\`. Optional: \`laneLeft = ArrowLeft\`,
  \`laneRight = ArrowRight\`.
- \`__GAME_META__\` shape:
  - \`subtype: 'runner'\`
  - \`autoRun: true\`
  - \`forwardAxis: 'x'\` (or \`'y'\`)
  - \`runSpeed: <number>\` (units per frame; integrate every step)
  - \`obstacles: [{ id, type, position, action }]\` — each entry mandatory
  - \`pickups: [{ id, type, position, value }]\` — optional but recommended
- \`snapshot()\` MUST expose: \`{ player: { x, y, vy }, distanceTraveled,
  obstaclesAvoided, pickupsCollected, gameOver, score, status }\`.
- \`progressPlan\` example:
  \`\`\`json
  [
    { "label": "auto-run", "input": "", "frames": 24, "metric": "distanceTraveled", "expect": "increase" },
    { "label": "jump dodge", "input": "Space", "frames": 12, "metric": "obstaclesAvoided", "expect": "increase" },
    { "label": "slide dodge", "input": "ArrowDown", "frames": 12, "metric": "obstaclesAvoided", "expect": "increase" }
  ]
  \`\`\`
- For movement metrics like \`player.x\`, \`distanceTraveled\`, \`obstaclesAvoided\`,
  \`pickupsCollected\`, \`expect\` MUST be one of \`"increase"\` / \`"decrease"\` /
  \`"change"\`, never a numeric target. Boolean expects (e.g. \`gameOver: true\`)
  are valid for terminal flags.

### Empty input for auto-run mechanics

Runner is the first genre with **legitimate empty / "none" input** in
\`progressPlan\`. The platformer validator currently rejects this because
platformer forward motion comes from ArrowRight presses; runner forward motion
comes from the time-step itself.

When generating a runner, declare the auto-run probe with \`input: ""\` (empty
string) — the validator should accept it for runner subtype because
\`autoRun: true\` in metadata makes forward motion implicit. If the validator
infrastructure rejects empty inputs uniformly, that's a gap to surface — runner
needs the validator to consult \`subtype\` before enforcing the "input must come
from controls" rule. **Do not** work around it by emitting bogus inputs like
\`"ArrowRight"\` for a game that ignores ArrowRight; that masks the architectural
gap and produces fake evidence.

### Smoke test contract

\`runSmokeTest()\` must drive \`step()\` and prove:

1. **Auto-run**: \`step("", 24)\` → assert \`after.distanceTraveled > before.distanceTraveled\`.
2. **Obstacle dodge**: \`step("Space", 12)\` over a jump-action obstacle → assert
   \`after.obstaclesAvoided > before.obstaclesAvoided\`.
3. **Pickup collect** (if pickups declared): \`step("", N)\` past a pickup
   → assert \`after.pickupsCollected > before.pickupsCollected\`.
4. **Death** (optional): drive into an unhandled obstacle → assert
   \`after.gameOver === true\`.

Coverage names returned by \`runSmokeTest().coverage\`:
\`coverage.mechanics = ["autoRun", "dodgeJump", "dodgeSlide", "collect"]\`,
\`coverage.stateChanges = ["distanceTraveled", "obstaclesAvoided", "pickupsCollected", "gameOver"]\`.`,
};

export const GAME_SKILL_REPAIR_HINTS: Record<string, string> = {
  "breakout": `| Failure Code | Hint |
|--------------|------|
| \`breakout 缺少 paddleX 可观测状态\` | Expose \`paddleX\` or \`paddle.x\` from \`snapshot()\`. Wire ArrowLeft/ArrowRight or left/right input so \`reset('paddleMove')\` followed by live \`step()\` changes that value. |
| \`breakout 缺少 ball 坐标/速度状态\` | Expose \`ball.x\`, \`ball.y\`, and velocity/speed such as \`ball.vx\`, \`ball.vy\`, \`ball.dx\`, \`ball.dy\`, or \`ball.speed\`. Make Space launch move ball coordinates in both \`reset('launch')\` and the real initial browser state. |
| \`breakout 缺少 wallBounceCount\` | Add \`wallBounceCount\` and increment it only when live ball-wall collision reverses direction. \`reset('wallBounce')\` should place the ball near a wall and prove \`wallBounceCount > before\`. |
| \`breakout 缺少 paddleBounceCount\` | Add \`paddleBounceCount\` and increment it only when the ball hits the paddle. \`reset('paddleBounce')\` should place the ball above the paddle and prove the counter increases. |
| \`breakout 缺少 brickCount/bricksRemaining 与 score\` | Expose \`brickCount\` or \`bricksRemaining\` plus \`score\`. \`reset('brickHit')\` should drive a real brick collision so brick count decreases or score increases. |
| \`breakout 缺少 powerups\` | Add all five required powerups: \`wide\`, \`multi\`, \`slow\`, \`through\`, and \`life\`. Each needs its own quoted \`reset('powerup:<type>')\` scenario and a matching snapshot delta. |
| \`breakout 缺少 deterministic reset scenario\` | Implement quoted reset ids for \`paddleMove\`, \`launch\`, \`wallBounce\`, \`paddleBounce\`, \`brickHit\`, \`win\`, \`lose\`, plus \`powerup:wide\`, \`powerup:multi\`, \`powerup:slow\`, \`powerup:through\`, and \`powerup:life\`. |
| \`breakout runtime 初始首屏没有可打砖块\` | Load a playable brick layout on the real initial screen. Do not create bricks only inside test-only reset scenarios. |
| \`breakout runtime 缺少真实 Space 发球证据\` | Normalize browser Space input from \`event.code === 'Space'\` or \`event.key === ' '\` into the same launch action used by the live loop, focus the game root on load/click, and prove ball coordinates change from initial load. |
| \`breakout runtime 缺少 powerup 触发证据\` | Repair each \`powerup:<type>\` probe so \`wide\` increases paddle width, \`multi\` increases ball count, \`slow\` decreases ball speed, \`through\` sets a truthy through flag, and \`life\` increases lives. |
| \`breakout runtime 缺少 win 证据\` | Make \`reset('win')\` reach \`status: 'won'\`, \`'win'\`, \`'complete'\`, or \`'cleared'\` after clearing bricks. |
| \`breakout runtime 缺少 lose 证据\` | Make \`reset('lose')\` reach \`status: 'lost'\`, \`'lose'\`, \`'failed'\`, or \`'gameover'\`, or set lives to 0 after a real miss/life-loss path. |

Other breakout-specific repair hints:

- Keep reset scenarios deterministic and short. Place ball, paddle, bricks, and
  powerups near the event under test, then drive the same live \`step()\` logic
  used by the playable game.
- If runtime evidence exists only in \`runSmokeTest().checks\`, also record
  \`breakoutScenarios\` probes with real before/after snapshots. The checker
  looks for named probes first for most breakout mechanics.
- If static validation passes but runtime fails, compare the exact snapshot
  paths in the failed hint against \`snapshot()\`. Missing aliases are enough to
  make a real mechanic invisible to validation.
- Do not fake powerup evidence with display-only labels. The checker accepts a
  typed after snapshot mention as a fallback, but robust games should expose
  the concrete state delta for each powerup.`,
  "platformer": `| Failure Code | Hint |
|--------------|------|
| \`missing_gameplay_mechanics\` | Add \`gameplayMechanics\` to \`__GAME_META__\` with \`enemies\`, \`blocks\`, \`abilities\`, \`gates\`, \`comboChallenge\` (each an array, never a map). Implement collision: stomp marks enemy defeated and bounces \`player.vy\`; bump marks block used and spawns the ability; ability changes movement; gate checks ability before route access. |
| \`gameplay_mechanics_without_runtime_evidence\` | Repair \`runSmokeTest()\` so it drives \`step()\` through stomp enemy, bump block, gain ability, unlock gate/route, and combo challenge — record coverage only after before/after snapshot changes prove each mechanic. |
| \`ability_gate_without_reachability\` | Make one ability change movement or interaction rules and unlock a real gated route. \`snapshot()\` should expose \`abilities\` and gate/route state, and \`runSmokeTest()\` must prove ability \`false → true\` followed by gate/route \`unreachable → reachable\`. |

Other platformer-specific repair hints:

- For platformers, add/repair \`gameplayMechanics\` with enemies, blocks, abilities,
  gates, and comboChallenge, wired to real \`step()\` gameplay and \`runSmokeTest()\`
  before/after snapshot evidence.
- Platformer \`gameplayMechanics.enemies\`, \`blocks\`, \`abilities\`, \`gates\`, and
  \`comboChallenge\` must be arrays; do not repair them as \`{ enemies: { ... } }\` or
  keyed object maps.
- If the full level path is too long, repair platformers with deterministic authored
  scenarios for stomp, bumpBlock, gainAbility, unlockGate, and comboChallenge using
  the live rules.
- Platformer coverage must prove \`stompEnemy\`, \`bumpBlock\`, \`gainAbility\`,
  \`unlockGate\`/\`routeReachableAfterAbility\`, and \`comboChallenge\`, with stateChanges
  for \`enemiesDefeated\`, \`player.vy\`/bounce, \`blocksUsed\`/\`spawnedReward\`,
  \`abilities\`, and \`gates\`/\`routes\`.`,
  "runner": `| Failure Code | Hint |
|--------------|------|
| \`missing_runner_loop_metadata\` | Declare \`__GAME_META__.autoRun = true\` plus \`forwardAxis\` ("x" or "y") and \`runSpeed\`. \`step()\` must increment \`distanceTraveled\` even with empty input — forward motion is implicit from the time-step. |
| \`missing_obstacle_metadata\` | Add \`__GAME_META__.obstacles = [{ id, type, position, action }]\` with at least one entry. The \`action\` field tells the player how to dodge (jump / slide / swap-lane). Hitting an unhandled obstacle should set \`gameOver: true\`. |
| \`runner_no_distance_progression\` | Make \`step()\` unconditionally advance \`distanceTraveled\` by \`runSpeed * frames\` (or per-frame integration) regardless of input. \`runSmokeTest()\` must take a before snapshot, call \`step("", N)\` with empty input, take an after snapshot, and assert \`after.distanceTraveled > before.distanceTraveled\`. |

Other runner-specific repair hints:

- If your engine ties forward motion to keyboard handling (e.g. ArrowRight
  increments \`player.x\`), refactor: forward speed should come from a \`runSpeed\`
  constant integrated each frame, not from input handling. Input should only
  control jump / slide / lane.
- If smoke says "distance not increasing", the most common cause is that
  \`step()\` early-returns on empty input. Remove that guard.
- If \`obstaclesAvoided\` doesn't increment, check that the obstacle's \`action\`
  field matches the input you're driving (Space for jump, ArrowDown for slide).`,
};
