export const DESIGN_ACCEPTANCE_CONTRACT = {
  VERSION: 1,
  MAX_ACCEPTANCE_CRITERIA: 24,
  MAX_LOCKED_REGIONS: 40,
  MAX_BRAND_REFS: 8,
  MAX_NOTES: 24,
  MAX_ID_CHARS: 80,
  MAX_TEXT_CHARS: 600,
} as const;
