export const DESIGN_CODE_HANDOFF = {
  VERSION: 1,
  MAX_SELECTED_VARIANTS: 3,
  MAX_INTERACTION_STATES: 12,
  MAX_NOTES: 16,
  MAX_QA_CHECKS: 16,
  MAX_ID_CHARS: 96,
  MAX_TEXT_CHARS: 800,
  MAX_PATH_CHARS: 1024,
} as const;
