// ============================================================================
// Shell Capability Manifest
// ============================================================================

import {
  makeShellCapabilityId,
  makeTauriCommandCapabilityId,
  SHELL_CAPABILITY_DOMAINS,
  shellCapabilityLayerForDomain,
  type ShellCapability,
  type ShellCapabilitiesManifest,
  type ShellCapabilityRisk,
} from '../shared/contract/shellCapabilities';
import { IPC_DOMAINS, type IPCDomain } from '../shared/ipc/domains';
import { sessionRoutes } from './ipc/domainRoutes/sessionRoutes';
import { MemorySchemas } from '../shared/ipc/schemas/memory';
import { DesktopSchemas } from '../shared/ipc/schemas/desktop';
import { TagSchemas } from '../shared/ipc/schemas/tag';
import { CronSchemas } from '../shared/ipc/schemas/cron';
import { PromptSchemas } from '../shared/ipc/schemas/prompt';
import { DiagnosticsSchemas } from '../shared/ipc/schemas/diagnostics';
import { DataSchemas } from '../shared/ipc/schemas/data';

const DEFAULT_SINCE_VERSION = '0.16.93';

const NATIVE_TAURI_COMMANDS = [
  'appshots_read_image_data_url',
  'appshots_read_image_data_url_by_id',
  'appshots_report_composer_slot',
  'appshots_set_enabled',
  'appshots_set_motion_enabled',
  'appshots_set_target_session',
  'appshots_skip_motion',
  'appshots_trigger',
  'check_for_update',
  'desktop_capture_screenshot',
  'desktop_get_app_icon',
  'desktop_get_capabilities',
  'desktop_get_collector_status',
  'desktop_get_frontmost_context',
  'desktop_get_permission_status',
  'desktop_list_recent_events',
  'desktop_open_system_settings',
  'desktop_request_microphone_permission',
  'desktop_start_audio_rec',
  'desktop_start_collector',
  'desktop_stop_audio_rec',
  'desktop_stop_collector',
  'desktop_update_analyze_text',
  'get_app_version',
  'install_update',
  'open_update_url',
  'pip_frame',
  'pip_control',
  'pip_controls',
  'pip_hide',
  'pip_show',
  'renderer_ready',
  'shutdown_web_server_for_update',
  'warm_compile_cache_after_install',
] as const;

// session 域自 RQ-183 刀 4 起从单源路由表派生（方案 2.4）：action 集合的真源是
// sessionRoutes 表，本清单不再手工维护——加/删 action 改表即可，这里自动跟。
// 手工只剩 since 版本（DEFAULT_SINCE_VERSION）与高危标记（HIGH_RISK_CAPABILITIES）。
// 其余域表化后照此逐域切换（挂后续单）；未表化域仍手工维护，由 domainRouteParity
// 的全域单向门盯「清单 ⊆ 实际 handler」+ 缺报棘轮。
const SESSION_TABLE_ACTIONS: readonly string[] = Object.keys(sessionRoutes.actions);

const CAPABILITY_DOMAIN_ACTIONS = {
  [IPC_DOMAINS.ACTIVITY]: [
    'getCurrentContext',
    'listProviders',
  ],
  [IPC_DOMAINS.ADMIN]: [
    'createInviteCode',
    'listControlPlaneAuditEvents',
    'listControlPlaneRolloutSummary',
    'listInviteCodes',
    'listUsers',
    'setUserAdmin',
    'setSharedRelay',
    'updateInviteCode',
  ],
  [IPC_DOMAINS.AGENT]: [
    'cancel',
    'closeAgent',
    'getSessionPermissionMode',
    'getTree',
    'getWorktreeReview',
    'interrupt',
    'pause',
    'permissionResponse',
    'resume',
    'send',
    'sendMemberInput',
    'setPermissionMode',
    'setSessionPermissionMode',
  ],
  [IPC_DOMAINS.AGENT_ENGINE]: [
    'detect',
    'get',
    'list',
    'listHistory',
    'listModels',
    'listSources',
    'previewHistory',
    'select',
    'selectModel',
  ],
  [IPC_DOMAINS.AGENT_REGISTRY]: [
    'list',
  ],
  [IPC_DOMAINS.AUTH]: [
    'clearSavedCredentials',
    'generateQuickToken',
    'getSavedCredentials',
    'getStatus',
    'getUser',
    'passwordResetCallback',
    'resetPassword',
    'saveCredentials',
    'signInEmail',
    'signInOAuth',
    'signInToken',
    'signOut',
    'signUpEmail',
    'updatePassword',
    'updateProfile',
  ],
  [IPC_DOMAINS.CAPABILITY]: [
    'installDraft',
    'list',
    'removeDraft',
    'setEnabled',
  ],
  [IPC_DOMAINS.CAPTURE]: [
    'capture',
    'delete',
    'get',
    'importFiles',
    'list',
    'search',
    'selectFiles',
    'stats',
    'wechatStatus',
  ],
  [IPC_DOMAINS.VOICE]: [
    'reportFailure',
    // 通话录音（N-L7-REC）：设置页与导出勾选框都读它，旧壳不认识要降级。
    'recordingOverview',
    // 声纹身份（N-L7-SPK）：热更新的 renderer 会调这四个，旧壳不认识就得降级，
    // 所以要在这里登记成壳能力（renderer-capability-diff 门守的就是这个）。
    'voiceprintClear',
    'voiceprintOverview',
    'voiceprintPrepareModel',
    'voiceprintRegister',
  ],
  [IPC_DOMAINS.CONNECTOR]: [
    'disconnect',
    'listNativeInventory',
    'listStatuses',
    'oauthCancelConnect',
    'oauthConnect',
    'oauthDisconnect',
    'oauthSaveDescriptor',
    'oauthSetSecret',
    'oauthStatus',
    'openApp',
    'probe',
    'remove',
    'repairPermission',
    'retry',
    'setNativeEnabled',
  ],
  // data 域：派生自 schema action 集合（== data 表 keys，parity 门三面对账），手工清单已删
  [IPC_DOMAINS.DATA]: DataSchemas.ACTIONS,
  [IPC_DOMAINS.FOLDER_TRUST]: [
    'get',
    'set',
  ],
  // cron 域：派生自 schema action 集合（== cron 表 keys，parity 门三面对账）；此前清单整域缺报 9 项
  [IPC_DOMAINS.CRON]: CronSchemas.ACTIONS,
  // desktop 域：派生自 schema action 集合（== desktop 表 keys，parity 门三面对账），手工清单已删
  [IPC_DOMAINS.DESKTOP]: DesktopSchemas.ACTIONS,
  // diagnostics 域：派生自 schema action 集合（== diagnostics 表 keys，parity 门三面对账），手工清单已删
  [IPC_DOMAINS.DIAGNOSTICS]: DiagnosticsSchemas.ACTIONS,
  [IPC_DOMAINS.GENERATIVE_UI]: [
    'applyEvent',
    'persistHtmlEdit',
    'resolveInstance',
    'resolveManifest',
  ],
  [IPC_DOMAINS.HOOK]: [
    'list',
    'openConfigFile',
    'revealConfigFolder',
  ],
  [IPC_DOMAINS.LIVE_PREVIEW]: [
    'applyTweak',
    'detectFramework',
    'getDevServerLogs',
    'getDevServerSession',
    'listDevServers',
    'ping',
    'resolveSourceLocation',
    'startDevServer',
    'stopDevServer',
    'validateDevServerUrl',
    'waitDevServerReady',
  ],
  [IPC_DOMAINS.MCP]: [
    'addServer',
    'cancelServerInstall',
    'getCatalog',
    'getServerStates',
    'getStatus',
    'listResources',
    'listTools',
    'reconnectServer',
    'refreshFromCloud',
    'removeServer',
    'setServerEnabled',
    'signOutServer',
  ],
  // memory 域：派生自 schema action 集合（== memoryRoutes 表 keys，parity 门三面对账），手工清单已删
  [IPC_DOMAINS.MEMORY]: MemorySchemas.ACTIONS,
  [IPC_DOMAINS.NOTIFICATION]: [
    'getRecent',
    'reportClientDelivery',
  ],
  [IPC_DOMAINS.OPENCHRONICLE]: [
    'getSettings',
    'getStatus',
    'setEnabled',
    'updateSettings',
  ],
  [IPC_DOMAINS.PII]: [
    'setup:cancel',
    'setup:isReady',
    'setup:start',
    'setup:status',
  ],
  [IPC_DOMAINS.PLANNING]: [
    'getErrors',
    'getFindings',
    'getPlan',
    'getState',
    'respondApproval',
  ],
  [IPC_DOMAINS.PROJECT]: [
    'addGoal',
    'addRole',
    'addSource',
    'artifactIssues',
    'artifacts',
    'createInvite',
    'createSpace',
    'create',
    'deleteProject',
    'detail',
    'gitStates',
    'list',
    'listCapabilitySelections',
    'listCloudCards',
    'listMembers',
    'listWithActivity',
    'promoteToCloudSpace',
    'promoteToSpace',
    'removeRole',
    'removeSource',
    'rename',
    'resyncCloudCards',
    'selectCapability',
    'setPrimarySource',
    'setDescription',
    'setStatus',
    'sources',
    'unselectCapability',
    'updateGoalStatus',
    'updateProject',
    'updateSourceAccess',
  ],
  [IPC_DOMAINS.QUEUED_INPUT]: [
    'enqueue',
    'list',
    'markSending',
    'reportSendOutcome',
    'reorder',
    'requeue',
    'retract',
    'sendNow',
    'update',
  ],
  [IPC_DOMAINS.LIBRARY]: [
    'addItem',
    'delete',
    'get',
    'getPin',
    'importFiles',
    'list',
    'pinnedItems',
    'setPin',
    'update',
  ],
  // prompt 域：派生自 schema action 集合（== prompt 表 keys，parity 门三面对账）；此前清单整域缺报 7 项
  [IPC_DOMAINS.PROMPT]: PromptSchemas.ACTIONS,
  [IPC_DOMAINS.PROVIDER]: [
    'discover_models',
    'getHealthStatus',
    'get_search_capabilities',
    'get_thinking_capabilities',
    'list_realtime_voice_providers',
    'run_diagnostics',
    'run_doctor',
    'save_realtime_voice_provider',
    'test_connection',
    'test_realtime_voice_provider',
  ],
  [IPC_DOMAINS.ROLES]: [
    'addBinding',
    'confirmDraft',
    'deleteMemory',
    'detail',
    'list',
    'listBoundCronJobs',
    'listBindings',
    'listDrafts',
    'rejectDraft',
    'removeBinding',
    'rolePackInstall',
    'rolePackList',
    'rolePackRetryMissingSkills',
    'rolePackUninstall',
    'setProactivity',
    'updateMemory',
    'updateEquipment',
    'updateDefinitionBody',
    'updatePersonalization',
    'updateVisual',
    'restoreFactory',
    'writeProjectMemory',
  ],
  // session 域：派生自 sessionRoutes 表（见上），手工清单已删
  [IPC_DOMAINS.SESSION]: SESSION_TABLE_ACTIONS,
  [IPC_DOMAINS.SESSION_AUTOMATION]: [
    'countPendingReview',
    'getSessionSummary',
    'listBySession',
    'listParkedApprovals',
    'listPendingReview',
    'markReviewed',
    'summarizeSessions',
  ],
  [IPC_DOMAINS.STATUS]: [
    'getCostStats',
    'getTodayCost',
  ],
  [IPC_DOMAINS.SURFACE_EXECUTION]: [
    'control',
    'deletePersistedTerminalFrames',
    'getFrame',
    'getOutput',
    'getPersistedTerminalFrame',
    'getSnapshot',
    'persistTerminalFrame',
  ],
  [IPC_DOMAINS.SETTINGS]: [
    'checkApiKeyConfigured',
    'get',
    'getAllServiceKeys',
    'getBudgetStatus',
    'getDevMode',
    'getServiceApiKey',
    'resolveProviderIconAsset',
    'saveProviderIconAsset',
    'set',
    'setBudgetConfig',
    'setDevMode',
    'setServiceApiKey',
    'testApiKey',
  ],
  [IPC_DOMAINS.SOUL]: [
    'getDefault',
    'getProfile',
    'getStatus',
    'resetProfile',
    'saveProfile',
  ],
  [IPC_DOMAINS.SYNC]: [
    'forceFull',
    'getStatus',
    'start',
    'stop',
  ],
  // tag 域：派生自 schema action 集合（== tag 表 keys，parity 门三面对账）；此前清单整域缺报 23 项
  [IPC_DOMAINS.TAG]: TagSchemas.ACTIONS,
  [IPC_DOMAINS.TASK]: [
    'cancel',
    'cleanup',
    'getAllStates',
    'getQueue',
    'getState',
    'getStats',
    'interrupt',
    'start',
  ],
  [IPC_DOMAINS.TERMINAL]: [
    'close',
    'list',
    'open',
    'resize',
    'snapshot',
    'write',
  ],
  [IPC_DOMAINS.TEAM]: [
    'confirmDraft',
    'knownRoles',
    'launchRecipe',
    'listDrafts',
    'recipeCreate',
    'recipeDelete',
    'recipeList',
    'recipeUpdate',
    'rejectDraft',
  ],
  [IPC_DOMAINS.UPDATE]: [
    'check',
    'download',
    'getInfo',
    'openFile',
    'openUrl',
    'prepareRuntimeAssets',
    'rendererBundleStatus',
    'runtimeAssetsStatus',
    'startAutoCheck',
    'stopAutoCheck',
  ],
  [IPC_DOMAINS.WORKSPACE]: [
    'createFile',
    'createFolder',
    'deleteBrand',
    'deleteCustomImageModel',
    'deleteCustomVideoModel',
    'downloadFile',
    'editDesignImage',
    'editImageByAnnotation',
    'expandDesignImage',
    'exportBundle',
    'exportCanvasPptx',
    'exportImagePdf',
    'exportPrototypePdf',
    'extractBrandFromImage',
    'generateDesignImage',
    'generateDesignMusic',
    'generateDesignVideo',
    'generateSlidesDeck',
    'generateSlidesOutline',
    'generateSlidesPreview',
    'getConfigScope',
    'getCurrent',
    'getDesignMdSummary',
    'getDesignSettings',
    'getFileMetadata',
    'getPublishInfo',
    'getShareLink',
    'importDesignImage',
    'importDesignImageFromPath',
    'inspectArchive',
    'inspectPresentation',
    'findFile',
    'previewPresentation',
    'publishVersion',
    'createShareLink',
    'updateShareLinkTtl',
    'pushShareLink',
    'revokeShareLink',
    'listBrands',
    'listCustomImageModels',
    'listCustomVideoModels',
    'listFiles',
    'listRecent',
    'listVisualImageModels',
    'listVisualMusicModels',
    'listVisualVideoModels',
    'openPath',
    'readBinary',
    'readFile',
    'removeRecent',
    'removeWatermarkDesignImage',
    'resolveDesignDir',
    'saveBinaryToDownloads',
    'saveBrand',
    'saveCustomImageModel',
    'saveCustomVideoModel',
    'saveTextToDownloads',
    'selectDirectory',
    'setActiveBrand',
    'setCurrent',
    'showItemInFolder',
    'updateDesignSettings',
    'writeFile',
  ],
} satisfies Partial<Record<IPCDomain, readonly string[]>>;

const HIGH_RISK_CAPABILITIES = new Set([
  makeShellCapabilityId(IPC_DOMAINS.AGENT, 'send'),
  // oauthSetSecret 落用户机密、oauthSaveDescriptor 改授权与注入边界、oauthConnect 发起
  // 对外授权；inferRisk 按动作名前缀猜会把 oauth* 判成 low，风险显示不出来。
  makeShellCapabilityId(IPC_DOMAINS.CONNECTOR, 'oauthConnect'),
  makeShellCapabilityId(IPC_DOMAINS.CONNECTOR, 'oauthSaveDescriptor'),
  makeShellCapabilityId(IPC_DOMAINS.CONNECTOR, 'oauthSetSecret'),
  makeShellCapabilityId(IPC_DOMAINS.DESKTOP, 'ensureManagedBrowserSession'),
  makeShellCapabilityId(IPC_DOMAINS.DESKTOP, 'importBrowserProfileCookies'),
  makeShellCapabilityId(IPC_DOMAINS.DESKTOP, 'observeComputerSurface'),
  makeShellCapabilityId(IPC_DOMAINS.DESKTOP, 'openManagedBrowserUrl'),
  // recoverHistory's import action writes sessions/messages/forks and creates a
  // receipt table; inferRisk's prefix regex doesn't match "recoverHistory" so it
  // would silently fall through to low.
  makeShellCapabilityId(IPC_DOMAINS.SESSION, 'recoverHistory'),
  makeShellCapabilityId(IPC_DOMAINS.SESSION, 'restoreWorkspaceFilesAtCheckpoint'),
  makeShellCapabilityId(IPC_DOMAINS.SESSION, 'turnCheckout'),
  makeShellCapabilityId(IPC_DOMAINS.SESSION, 'turnRedo'),
  makeShellCapabilityId(IPC_DOMAINS.SURFACE_EXECUTION, 'control'),
  makeShellCapabilityId(IPC_DOMAINS.TERMINAL, 'write'),
  makeShellCapabilityId(IPC_DOMAINS.WORKSPACE, 'writeFile'),
  makeTauriCommandCapabilityId('install_update'),
]);

function inferRisk(domain: string, action: string): ShellCapabilityRisk {
  const id = makeShellCapabilityId(domain, action);
  if (HIGH_RISK_CAPABILITIES.has(id)) return 'high';
  if (/^(add|archive|cancel|capture|clear|close|confirm|create|delete|disconnect|download|force|import|install|interrupt|open|pause|prepare|probe|refresh|reject|remove|rename|repair|report|reset|resume|resync|retry|save|select|send|set|sign|start|stop|switch|unarchive|update|write)/i.test(action)) {
    return 'medium';
  }
  return 'low';
}

export function getShellCapabilities(): ShellCapability[] {
  const domainCapabilities = Object.entries(CAPABILITY_DOMAIN_ACTIONS)
    .flatMap(([domain, actions]) => actions.map((action) => ({
      id: makeShellCapabilityId(domain, action),
      domain,
      action,
      layer: shellCapabilityLayerForDomain(domain),
      since: DEFAULT_SINCE_VERSION,
      risk: inferRisk(domain, action),
    })));
  const nativeCapabilities = NATIVE_TAURI_COMMANDS.map((command) => ({
    id: makeTauriCommandCapabilityId(command),
    domain: SHELL_CAPABILITY_DOMAINS.TAURI,
    action: command,
    layer: shellCapabilityLayerForDomain(SHELL_CAPABILITY_DOMAINS.TAURI),
    since: DEFAULT_SINCE_VERSION,
    risk: inferRisk(SHELL_CAPABILITY_DOMAINS.TAURI, command),
  }));

  return [...domainCapabilities, ...nativeCapabilities]
    .sort((a, b) => a.id.localeCompare(b.id));
}

export function getShellCapabilityIds(): string[] {
  return getShellCapabilities().map((capability) => capability.id);
}

export function getShellCapabilitiesManifest(
  appVersion: string,
  generatedAt = new Date().toISOString(),
): ShellCapabilitiesManifest {
  return {
    schemaVersion: 1,
    appVersion,
    generatedAt,
    capabilities: getShellCapabilities(),
  };
}
