// ============================================================================
// Generation Metadata - Defines all 8 generations without prompts
// ============================================================================

import type { Generation, GenerationId } from '../../shared/types';

// 版本号对应代际：Gen1=v1.0, Gen2=v2.0, ..., Gen8=v8.0
export const GENERATION_DEFINITIONS: Record<GenerationId, Omit<Generation, 'systemPrompt'>> = {
  gen1: {
    id: 'gen1',
    name: '基础工具期',
    version: 'v1.0',
    description: '最小可用的编程助手，支持基础文件操作和命令执行',
    tools: ['bash', 'read_file', 'write_file', 'edit_file'],
    promptMetadata: {
      lineCount: 85,
      toolCount: 4,
      ruleCount: 15,
    },
  },
  gen2: {
    id: 'gen2',
    name: '生态融合期',
    version: 'v2.0',
    description: '支持外部系统集成、文件搜索和 IDE 协作',
    tools: ['bash', 'read_file', 'write_file', 'edit_file', 'glob', 'grep', 'list_directory'],
    promptMetadata: {
      lineCount: 120,
      toolCount: 7,
      ruleCount: 25,
    },
  },
  gen3: {
    id: 'gen3',
    name: '智能规划期',
    version: 'v3.0',
    description: '支持多代理编排、任务规划和进度追踪',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
    ],
    promptMetadata: {
      lineCount: 188,
      toolCount: 12,
      ruleCount: 45,
    },
  },
  gen4: {
    id: 'gen4',
    name: '工业化系统期',
    version: 'v4.0',
    description: '完整的插件生态、技能系统和高级自动化',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
      'skill',
      'web_fetch',
      'web_search',
      'notebook_edit',
    ],
    promptMetadata: {
      lineCount: 169,
      toolCount: 15,
      ruleCount: 40,
    },
  },
  gen5: {
    id: 'gen5',
    name: '认知增强期',
    version: 'v5.0',
    description: '长期记忆、RAG 检索增强、自主学习和代码索引',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
      'skill',
      'web_fetch',
      'web_search',
      'notebook_edit',
      'memory_store',
      'memory_search',
      'code_index',
      'auto_learn',
    ],
    promptMetadata: {
      lineCount: 250,
      toolCount: 18,
      ruleCount: 55,
    },
  },
  gen6: {
    id: 'gen6',
    name: '视觉操控期',
    version: 'v6.0',
    description: 'Computer Use - 直接操控桌面、浏览器和 GUI 界面',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
      'skill',
      'web_fetch',
      'web_search',
      'notebook_edit',
      'memory_store',
      'memory_search',
      'code_index',
      'auto_learn',
      'screenshot',
      'computer_use',
      'browser_navigate',
      'browser_action',
    ],
    promptMetadata: {
      lineCount: 300,
      toolCount: 22,
      ruleCount: 60,
    },
  },
  gen7: {
    id: 'gen7',
    name: '多代理协同期',
    version: 'v7.0',
    description: 'Multi-Agent - 多个专业代理协同完成复杂任务',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
      'skill',
      'web_fetch',
      'web_search',
      'notebook_edit',
      'memory_store',
      'memory_search',
      'code_index',
      'auto_learn',
      'screenshot',
      'computer_use',
      'browser_navigate',
      'browser_action',
      'spawn_agent',
      'agent_message',
      'workflow_orchestrate',
    ],
    promptMetadata: {
      lineCount: 350,
      toolCount: 25,
      ruleCount: 70,
    },
  },
  gen8: {
    id: 'gen8',
    name: '自我进化期',
    version: 'v8.0',
    description: 'Self-Evolution - 从经验中学习、自我优化和动态创建工具',
    tools: [
      'bash',
      'read_file',
      'write_file',
      'edit_file',
      'glob',
      'grep',
      'list_directory',
      'task',
      'todo_write',
      'ask_user_question',
      'skill',
      'web_fetch',
      'web_search',
      'notebook_edit',
      'memory_store',
      'memory_search',
      'code_index',
      'auto_learn',
      'screenshot',
      'computer_use',
      'browser_navigate',
      'browser_action',
      'spawn_agent',
      'agent_message',
      'workflow_orchestrate',
      'strategy_optimize',
      'tool_create',
      'self_evaluate',
      'learn_pattern',
    ],
    promptMetadata: {
      lineCount: 400,
      toolCount: 29,
      ruleCount: 80,
    },
  },
};
