// ============================================================================
// PPT Generate Tool - 生成 PowerPoint 演示文稿 (.pptx)
// ============================================================================

import type { Tool, ToolContext, ToolExecutionResult } from '../toolRegistry';
import * as fs from 'fs';
import * as path from 'path';

// Use require for pptxgenjs (CJS compatible with Electron)
function getPptxGenJS() {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const PptxGenJS = require('pptxgenjs');
  return PptxGenJS;
}

// PPT 风格主题
type PPTTheme = 'professional' | 'tech' | 'minimal' | 'vibrant';

interface PPTGenerateParams {
  topic: string;
  content?: string;
  slides_count?: number;
  theme?: PPTTheme;
  output_path?: string;
}

// 主题配置
const themeConfigs: Record<PPTTheme, {
  titleColor: string;
  textColor: string;
  bgColor: string;
  accentColor: string;
  fontFace: string;
}> = {
  professional: {
    titleColor: '1a365d',
    textColor: '2d3748',
    bgColor: 'ffffff',
    accentColor: '3182ce',
    fontFace: 'Arial',
  },
  tech: {
    titleColor: '0d9488',
    textColor: 'e2e8f0',
    bgColor: '0f172a',
    accentColor: '22d3ee',
    fontFace: 'Consolas',
  },
  minimal: {
    titleColor: '1f2937',
    textColor: '4b5563',
    bgColor: 'f9fafb',
    accentColor: '6b7280',
    fontFace: 'Helvetica',
  },
  vibrant: {
    titleColor: '7c3aed',
    textColor: '1f2937',
    bgColor: 'ffffff',
    accentColor: 'ec4899',
    fontFace: 'Arial',
  },
};

export const pptGenerateTool: Tool = {
  name: 'ppt_generate',
  description: `生成 PowerPoint 演示文稿（.pptx 文件）。

生成的文件可以直接用 Microsoft PowerPoint、Keynote 或 WPS 打开。

**主题选项：**
- professional: 专业商务风格（蓝白配色）
- tech: 科技风格（深色背景，青色点缀）
- minimal: 极简风格（浅灰背景）
- vibrant: 活力风格（紫粉配色）

**使用示例：**
\`\`\`
ppt_generate { "topic": "产品介绍", "slides_count": 5, "theme": "professional" }
ppt_generate { "topic": "技术分享", "content": "# 第一章\\n- 要点1\\n- 要点2", "theme": "tech" }
\`\`\``,
  generations: ['gen5', 'gen6', 'gen7', 'gen8'],
  requiresPermission: true,
  permissionLevel: 'write',
  inputSchema: {
    type: 'object',
    properties: {
      topic: {
        type: 'string',
        description: '演示文稿的主题/标题',
      },
      content: {
        type: 'string',
        description: '详细内容大纲（Markdown 格式，可选）',
      },
      slides_count: {
        type: 'number',
        description: '幻灯片数量（默认: 5）',
        default: 5,
      },
      theme: {
        type: 'string',
        enum: ['professional', 'tech', 'minimal', 'vibrant'],
        description: '主题风格（默认: professional）',
        default: 'professional',
      },
      output_path: {
        type: 'string',
        description: '输出文件路径（默认: 工作目录下的 presentation-{timestamp}.pptx）',
      },
    },
    required: ['topic'],
  },

  async execute(
    params: Record<string, unknown>,
    context: ToolContext
  ): Promise<ToolExecutionResult> {
    const {
      topic,
      content,
      slides_count = 5,
      theme = 'professional',
      output_path,
    } = params as unknown as PPTGenerateParams;

    try {
      // 获取 PptxGenJS
      const Pptx = getPptxGenJS();

      // 确定输出路径
      const timestamp = Date.now();
      const fileName = `presentation-${timestamp}.pptx`;
      const outputDir = output_path
        ? path.dirname(output_path)
        : context.workingDirectory;
      const finalPath = output_path || path.join(outputDir, fileName);

      // 确保目录存在
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      // 创建演示文稿
      const pptx = new Pptx();
      const themeConfig = themeConfigs[theme as PPTTheme] || themeConfigs.professional;

      // 设置演示文稿属性
      pptx.author = 'Code Agent';
      pptx.title = topic;
      pptx.subject = topic;
      pptx.company = 'Generated by Code Agent';

      // 解析内容或生成占位内容
      const slides = content
        ? parseContentToSlides(content, slides_count)
        : generatePlaceholderSlides(topic, slides_count);

      // 生成幻灯片
      for (let i = 0; i < slides.length; i++) {
        const slideData = slides[i];
        const slide = pptx.addSlide();

        // 设置背景色
        slide.background = { color: themeConfig.bgColor };

        if (i === 0) {
          // 标题页
          slide.addText(slideData.title, {
            x: 0.5,
            y: '40%',
            w: '90%',
            h: 1.5,
            fontSize: 44,
            fontFace: themeConfig.fontFace,
            color: themeConfig.titleColor,
            bold: true,
            align: 'center',
          });

          if (slideData.subtitle) {
            slide.addText(slideData.subtitle, {
              x: 0.5,
              y: '55%',
              w: '90%',
              h: 0.8,
              fontSize: 24,
              fontFace: themeConfig.fontFace,
              color: themeConfig.textColor,
              align: 'center',
            });
          }
        } else if (i === slides.length - 1 && slideData.title.includes('谢谢') || slideData.title.includes('Thank')) {
          // 结束页
          slide.addText(slideData.title, {
            x: 0.5,
            y: '45%',
            w: '90%',
            h: 1.5,
            fontSize: 48,
            fontFace: themeConfig.fontFace,
            color: themeConfig.accentColor,
            bold: true,
            align: 'center',
          });
        } else {
          // 内容页
          // 标题
          slide.addText(slideData.title, {
            x: 0.5,
            y: 0.5,
            w: '90%',
            h: 1,
            fontSize: 32,
            fontFace: themeConfig.fontFace,
            color: themeConfig.titleColor,
            bold: true,
          });

          // 分隔线
          slide.addShape('rect', {
            x: 0.5,
            y: 1.4,
            w: 2,
            h: 0.05,
            fill: { color: themeConfig.accentColor },
          });

          // 内容要点
          if (slideData.points && slideData.points.length > 0) {
            const bulletPoints = slideData.points.map(point => ({
              text: point,
              options: {
                bullet: { type: 'bullet', color: themeConfig.accentColor },
                fontSize: 20,
                fontFace: themeConfig.fontFace,
                color: themeConfig.textColor,
                paraSpaceAfter: 12,
              },
            }));

            slide.addText(bulletPoints, {
              x: 0.5,
              y: 1.8,
              w: '90%',
              h: 4,
              valign: 'top',
            });
          }
        }
      }

      // 保存文件
      await pptx.writeFile({ fileName: finalPath });

      // 获取文件信息
      const stats = fs.statSync(finalPath);

      return {
        success: true,
        output: `✅ PPT 已生成！

📄 文件路径: ${finalPath}
🎨 主题风格: ${theme}
📊 幻灯片数量: ${slides.length}
📦 文件大小: ${formatFileSize(stats.size)}

点击上方文件路径可直接打开。`,
        metadata: {
          filePath: finalPath,
          fileName: path.basename(finalPath),
          fileSize: stats.size,
          slidesCount: slides.length,
          theme,
          // 附件信息 - 供前端展示
          attachment: {
            id: `ppt-${timestamp}`,
            type: 'file',
            category: 'document',
            name: path.basename(finalPath),
            path: finalPath,
            size: stats.size,
            mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
          },
        },
      };
    } catch (error: any) {
      return {
        success: false,
        error: `PPT 生成失败: ${error.message}`,
      };
    }
  },
};

// 解析 Markdown 内容为幻灯片数据
interface SlideData {
  title: string;
  subtitle?: string;
  points?: string[];
}

function parseContentToSlides(content: string, maxSlides: number): SlideData[] {
  const slides: SlideData[] = [];
  const lines = content.split('\n').filter(l => l.trim());

  let currentSlide: SlideData | null = null;

  for (const line of lines) {
    const trimmed = line.trim();

    // 一级标题 - 新幻灯片
    if (trimmed.startsWith('# ')) {
      if (currentSlide) {
        slides.push(currentSlide);
      }
      currentSlide = {
        title: trimmed.replace(/^#\s*/, ''),
        points: [],
      };
    }
    // 二级标题 - 副标题或新幻灯片
    else if (trimmed.startsWith('## ')) {
      if (currentSlide && !currentSlide.points?.length) {
        currentSlide.subtitle = trimmed.replace(/^##\s*/, '');
      } else {
        if (currentSlide) {
          slides.push(currentSlide);
        }
        currentSlide = {
          title: trimmed.replace(/^##\s*/, ''),
          points: [],
        };
      }
    }
    // 三级标题 - 作为要点
    else if (trimmed.startsWith('### ')) {
      if (currentSlide) {
        currentSlide.points = currentSlide.points || [];
        currentSlide.points.push(trimmed.replace(/^###\s*/, ''));
      }
    }
    // 列表项
    else if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || trimmed.match(/^\d+\.\s/)) {
      if (currentSlide) {
        currentSlide.points = currentSlide.points || [];
        currentSlide.points.push(trimmed.replace(/^[-*]\s*/, '').replace(/^\d+\.\s*/, ''));
      }
    }
    // 普通文本行作为副标题或要点
    else if (trimmed && currentSlide) {
      if (!currentSlide.subtitle && !currentSlide.points?.length) {
        currentSlide.subtitle = trimmed;
      } else {
        currentSlide.points = currentSlide.points || [];
        currentSlide.points.push(trimmed);
      }
    }
  }

  if (currentSlide) {
    slides.push(currentSlide);
  }

  // 如果没有解析出幻灯片，创建一个基于内容的幻灯片
  if (slides.length === 0) {
    slides.push({
      title: '内容概述',
      points: content.split('\n').filter(l => l.trim()).slice(0, 5),
    });
  }

  // 限制幻灯片数量
  return slides.slice(0, maxSlides);
}

// 生成占位幻灯片
function generatePlaceholderSlides(topic: string, count: number): SlideData[] {
  const slides: SlideData[] = [
    {
      title: topic,
      subtitle: 'Generated by Code Agent',
    },
  ];

  const sectionTitles = [
    '背景介绍',
    '核心内容',
    '详细分析',
    '案例展示',
    '实施方案',
    '预期效果',
    '总结展望',
  ];

  for (let i = 0; i < count - 2 && i < sectionTitles.length; i++) {
    slides.push({
      title: sectionTitles[i],
      points: [
        '要点内容 1',
        '要点内容 2',
        '要点内容 3',
      ],
    });
  }

  slides.push({
    title: '谢谢观看',
  });

  return slides;
}

// 格式化文件大小
function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
