// ============================================================================
// Provider Registry - 模型能力注册表
// ============================================================================

import type { ProviderConfig } from '../../shared/types';

export const PROVIDER_REGISTRY: Record<string, ProviderConfig> = {
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    requiresApiKey: true,
    baseUrl: 'https://api.deepseek.com/v1',
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek Chat',
        capabilities: ['general', 'code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek-coder',
        name: 'DeepSeek Coder',
        capabilities: ['code'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  claude: {
    id: 'claude',
    name: 'Anthropic Claude',
    requiresApiKey: true,
    baseUrl: 'https://api.anthropic.com/v1',
    models: [
      {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude 4 Sonnet',
        capabilities: ['general', 'code', 'vision', 'gui'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        capabilities: ['general', 'code', 'vision', 'gui'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        capabilities: ['fast', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    requiresApiKey: true,
    baseUrl: 'https://api.openai.com/v1',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        capabilities: ['fast', 'general'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq (极速推理)',
    requiresApiKey: true,
    baseUrl: 'https://api.groq.com/openai/v1',
    models: [
      // === Llama 4 (2026最新) ===
      {
        id: 'meta-llama/llama-4-maverick-17b-128e-instruct',
        name: 'Llama 4 Maverick (最新)',
        capabilities: ['fast', 'general', 'code', 'vision'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'meta-llama/llama-4-scout-17b-16e-instruct',
        name: 'Llama 4 Scout (多模态)',
        capabilities: ['fast', 'general', 'code', 'vision'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      // === Llama 3.3 (稳定版) ===
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B (稳定)',
        capabilities: ['fast', 'general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B (极速)',
        capabilities: ['fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === Kimi K2 (Groq 托管) ===
      {
        id: 'moonshotai/kimi-k2-instruct',
        name: 'Kimi K2 (Groq极速)',
        capabilities: ['fast', 'general', 'code'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === 复合模型 ===
      {
        id: 'groq/compound',
        name: 'Groq Compound (智能路由)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  local: {
    id: 'local',
    name: 'Local (Ollama)',
    requiresApiKey: false,
    baseUrl: 'http://localhost:11434/v1',
    models: [
      {
        id: 'qwen2.5-coder:7b',
        name: 'Qwen 2.5 Coder 7B',
        capabilities: ['code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  zhipu: {
    id: 'zhipu',
    name: '智谱 GLM',
    requiresApiKey: true,
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    codingBaseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
    models: [
      // === 旗舰模型 ===
      {
        id: 'glm-4.7',
        name: 'GLM-4.7 (旗舰语言)',
        capabilities: ['general', 'code', 'reasoning'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        useCodingEndpoint: true,
      },
      {
        id: 'glm-4.6v',
        name: 'GLM-4.6V (旗舰视觉)',
        capabilities: ['vision', 'reasoning', 'gui'],
        maxTokens: 16384,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          maxVisionTokens: 4096,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '同尺寸SOTA视觉推理模型',
        },
      },
      // === 免费模型 ===
      {
        id: 'glm-4.7-flash',
        name: 'GLM-4.7 Flash (免费语言)',
        capabilities: ['general', 'code', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'glm-4.6v-flash',
        name: 'GLM-4.6V Flash (免费视觉)',
        capabilities: ['vision', 'fast', 'gui'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          maxVisionTokens: 4096,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '免费视觉推理模型',
        },
      },
      // === 代码专用 ===
      {
        id: 'codegeex-4',
        name: 'CodeGeeX-4 (代码专用)',
        capabilities: ['code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === 图像生成 (免费) ===
      {
        id: 'cogview-3-flash',
        name: 'CogView-3 Flash (文生图)',
        capabilities: ['general'],
        maxTokens: 1024,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: false,
        isGenerationModel: true,
        generationType: 'image',
      },
      // === 视频生成 (免费，异步) ===
      {
        id: 'cogvideox-flash',
        name: 'CogVideoX Flash (文生视频)',
        capabilities: ['general'],
        maxTokens: 1024,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: false,
        isGenerationModel: true,
        generationType: 'video',
        isAsync: true,
      },
    ],
  },
  qwen: {
    id: 'qwen',
    name: '通义千问 (百炼)',
    requiresApiKey: true,
    // 注意：国内用 dashscope.aliyuncs.com，新加坡用 dashscope-intl.aliyuncs.com
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    models: [
      {
        id: 'qwen-max',
        name: 'Qwen Max',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'qwen-turbo',
        name: 'Qwen Turbo',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === 视觉模型 ===
      {
        id: 'qwen3-vl-max',
        name: 'Qwen3 VL Max (视觉旗舰)',
        capabilities: ['vision', 'gui'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '最强视觉理解',
        },
      },
      {
        id: 'qwen3-vl-plus',
        name: 'Qwen3 VL Plus (视频理解)',
        capabilities: ['vision', 'gui'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        supportsVideo: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp', 'mp4'],
          note: '支持超长视频理解',
        },
      },
      {
        id: 'qwen3-vl-flash',
        name: 'Qwen3 VL Flash (快速视觉)',
        capabilities: ['vision', 'fast'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '快速视觉识别',
        },
      },
      // === 全模态 ===
      {
        id: 'qwen-omni-turbo',
        name: 'Qwen Omni (全模态)',
        capabilities: ['vision', 'general'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        supportsVideo: true,
        supportsAudio: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp', 'mp4', 'mp3', 'wav'],
          note: '文本+图片+音频+视频全模态输入',
        },
      },
      // === 代码模型 ===
      {
        id: 'qwen-coder-plus',
        name: 'Qwen Coder Plus (代码专用)',
        capabilities: ['code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    requiresApiKey: true,
    baseUrl: 'https://api.moonshot.cn/v1',
    models: [
      {
        id: 'kimi-k2.5',
        name: 'Kimi K2.5 (包月套餐)',
        capabilities: ['general', 'code', 'reasoning', 'longContext', 'unlimited'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'moonshot-v1-8k',
        name: 'Moonshot V1 8K',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'moonshot-v1-32k',
        name: 'Moonshot V1 32K',
        capabilities: ['general', 'code'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'moonshot-v1-128k',
        name: 'Moonshot V1 128K (超长上下文)',
        capabilities: ['general', 'code'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    requiresApiKey: true,
    baseUrl: 'https://api.minimax.chat/v1',
    models: [
      {
        id: 'abab6.5s-chat',
        name: 'abab6.5s (快速)',
        capabilities: ['general', 'code', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab6.5-chat',
        name: 'abab6.5',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab5.5s-chat',
        name: 'abab5.5s (快速)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab5.5-chat',
        name: 'abab5.5',
        capabilities: ['general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    requiresApiKey: true,
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: [
      // === Gemini 3 (2026最新) ===
      {
        id: 'gemini-3-pro',
        name: 'Gemini 3 Pro (旗舰)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash (快速)',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      // === Gemini 2.5 (稳定版) ===
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'gemini-2.5-flash-lite',
        name: 'Gemini 2.5 Flash Lite (便宜)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    requiresApiKey: true,
    baseUrl: 'https://api.perplexity.ai',
    models: [
      {
        id: 'sonar-pro',
        name: 'Sonar Pro (联网搜索)',
        capabilities: ['search', 'general'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'sonar',
        name: 'Sonar (联网搜索)',
        capabilities: ['search', 'fast'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter (中转)',
    requiresApiKey: true,
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [
      // === Google Gemini 3 (2026最新) ===
      {
        id: 'google/gemini-3-flash-preview',
        name: 'Gemini 3 Flash (最新)',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'google/gemini-3-pro-preview',
        name: 'Gemini 3 Pro (最强)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'google/gemma-3n-e2b-it:free',
        name: 'Gemma 3 (免费)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === Anthropic Claude 4.5 (2026最新) ===
      {
        id: 'anthropic/claude-opus-4.5',
        name: 'Claude Opus 4.5 (旗舰)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'anthropic/claude-sonnet-4.5',
        name: 'Claude Sonnet 4.5',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        name: 'Claude Haiku 4.5 (快速)',
        capabilities: ['fast', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      // === OpenAI GPT-5.2 (2026最新) ===
      {
        id: 'openai/gpt-5.2',
        name: 'GPT-5.2 (最新)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'openai/gpt-5.2-codex',
        name: 'GPT-5.2 Codex (代码)',
        capabilities: ['code', 'reasoning'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      // === Meta Llama 4 (2026最新) ===
      {
        id: 'meta-llama/llama-3.3-70b-instruct:free',
        name: 'Llama 3.3 70B (免费)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'meta-llama/llama-4-maverick',
        name: 'Llama 4 Maverick (最新)',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      // === DeepSeek V3.2 (2026最新) ===
      {
        id: 'deepseek/deepseek-v3.2',
        name: 'DeepSeek V3.2 (最新)',
        capabilities: ['general', 'code'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek/deepseek-r1-0528:free',
        name: 'DeepSeek R1 (免费推理)',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
};
