// ============================================================================
// Provider Registry - Model provider configurations
// ============================================================================

import type { ProviderConfig } from '../../shared/types';

export const PROVIDER_REGISTRY: Record<string, ProviderConfig> = {
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    requiresApiKey: true,
    baseUrl: 'https://api.deepseek.com/v1',
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek Chat',
        capabilities: ['general', 'code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek-coder',
        name: 'DeepSeek Coder',
        capabilities: ['code'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  claude: {
    id: 'claude',
    name: 'Anthropic Claude',
    requiresApiKey: true,
    baseUrl: 'https://api.anthropic.com/v1',
    models: [
      {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude 4 Sonnet',
        capabilities: ['general', 'code', 'vision', 'gui'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        capabilities: ['general', 'code', 'vision', 'gui'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        capabilities: ['fast', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
    ],
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    requiresApiKey: true,
    baseUrl: 'https://api.openai.com/v1',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        capabilities: ['fast', 'general'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    requiresApiKey: true,
    baseUrl: 'https://api.groq.com/openai/v1',
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        capabilities: ['fast', 'general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        capabilities: ['fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'llama-3.2-11b-vision-preview',
        name: 'Llama 3.2 11B Vision',
        capabilities: ['fast', 'vision'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'mixtral-8x7b-32768',
        name: 'Mixtral 8x7B',
        capabilities: ['fast', 'code'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  local: {
    id: 'local',
    name: 'Local (Ollama)',
    requiresApiKey: false,
    baseUrl: 'http://localhost:11434/v1',
    models: [
      {
        id: 'qwen2.5-coder:7b',
        name: 'Qwen 2.5 Coder 7B',
        capabilities: ['code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  zhipu: {
    id: 'zhipu',
    name: '智谱 GLM',
    requiresApiKey: true,
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    codingBaseUrl: 'https://open.bigmodel.cn/api/coding/paas/v4',
    models: [
      {
        id: 'glm-4.7',
        name: 'GLM-4.7 (Coding 套餐)',
        capabilities: ['general', 'code', 'reasoning'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        useCodingEndpoint: true,
      },
      {
        id: 'glm-4-flash',
        name: 'GLM-4 Flash',
        capabilities: ['general', 'code', 'fast'],
        maxTokens: 4096,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'glm-4-plus',
        name: 'GLM-4 Plus',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'glm-4-long',
        name: 'GLM-4 Long',
        capabilities: ['general', 'code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'glm-4v-plus',
        name: 'GLM-4V Plus (视觉)',
        capabilities: ['vision', 'gui'],
        maxTokens: 2048,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          maxVisionTokens: 2048,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '智谱高性能视觉模型，支持 base64 和 URL',
        },
      },
      {
        id: 'glm-4v-flash',
        name: 'GLM-4V Flash (视觉)',
        capabilities: ['vision', 'fast'],
        maxTokens: 1024,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: false,
          supportsUrl: true,
          maxVisionTokens: 1024,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
          note: '智谱快速视觉模型，仅支持 URL 输入',
        },
      },
      {
        id: 'codegeex-4',
        name: 'CodeGeeX-4 (代码专用)',
        capabilities: ['code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  qwen: {
    id: 'qwen',
    name: '通义千问',
    requiresApiKey: true,
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    models: [
      {
        id: 'qwen-max',
        name: 'Qwen Max',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'qwen-turbo',
        name: 'Qwen Turbo',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'qwen-vl-max',
        name: 'Qwen VL Max (视觉)',
        capabilities: ['vision'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
      {
        id: 'qwen-coder-plus',
        name: 'Qwen Coder Plus (代码专用)',
        capabilities: ['code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    requiresApiKey: true,
    baseUrl: 'https://api.moonshot.cn/v1',
    models: [
      {
        id: 'moonshot-v1-8k',
        name: 'Moonshot V1 8K',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'moonshot-v1-32k',
        name: 'Moonshot V1 32K',
        capabilities: ['general', 'code'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'moonshot-v1-128k',
        name: 'Moonshot V1 128K (超长上下文)',
        capabilities: ['general', 'code'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    requiresApiKey: true,
    baseUrl: 'https://api.minimax.chat/v1',
    models: [
      {
        id: 'abab6.5s-chat',
        name: 'abab6.5s (快速)',
        capabilities: ['general', 'code', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab6.5-chat',
        name: 'abab6.5',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab5.5s-chat',
        name: 'abab5.5s (快速)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'abab5.5-chat',
        name: 'abab5.5',
        capabilities: ['general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    requiresApiKey: true,
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    models: [
      {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro (最强)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'gemini-2.5-flash-lite',
        name: 'Gemini 2.5 Flash Lite (最便宜)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    requiresApiKey: true,
    baseUrl: 'https://api.perplexity.ai',
    models: [
      {
        id: 'sonar-pro',
        name: 'Sonar Pro (联网搜索)',
        capabilities: ['search', 'general'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'sonar',
        name: 'Sonar (联网搜索)',
        capabilities: ['search', 'fast'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter (中转)',
    requiresApiKey: true,
    baseUrl: 'https://openrouter.ai/api/v1',
    models: [
      {
        id: 'google/gemini-2.0-flash-001',
        name: 'Gemini 2.0 Flash',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'google/gemini-2.0-flash-thinking-exp:free',
        name: 'Gemini 2.0 Flash Thinking (免费)',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'google/gemini-exp-1206:free',
        name: 'Gemini Exp 1206 (免费)',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'anthropic/claude-3.5-sonnet',
        name: 'Claude 3.5 Sonnet (中转)',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'anthropic/claude-3.5-haiku',
        name: 'Claude 3.5 Haiku (中转)',
        capabilities: ['fast', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'openai/gpt-4o',
        name: 'GPT-4o (中转)',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 4096,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'openai/gpt-4o-mini',
        name: 'GPT-4o Mini (中转)',
        capabilities: ['fast', 'general'],
        maxTokens: 4096,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
      },
      {
        id: 'deepseek/deepseek-chat',
        name: 'DeepSeek Chat (中转)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
      },
      {
        id: 'deepseek/deepseek-r1',
        name: 'DeepSeek R1 (中转)',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
      },
    ],
  },
};
