// ============================================================================
// Provider Registry - additional provider catalog
// ============================================================================

import type { ProviderConfig } from '../../shared/contract';
import { MODEL_API_ENDPOINTS } from '../../shared/constants';

export const ADDITIONAL_PROVIDER_REGISTRY: Record<string, ProviderConfig> = {
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.minimax,
    models: [
      {
        id: 'abab6.5s-chat',
        name: 'abab6.5s (快速)',
        capabilities: ['general', 'code', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'abab6.5-chat',
        name: 'abab6.5',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'abab5.5s-chat',
        name: 'abab5.5s (快速)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'abab5.5-chat',
        name: 'abab5.5',
        capabilities: ['general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.gemini,
    models: [
      // === Gemini 3 (2026最新) ===
      {
        id: 'gemini-3-pro',
        name: 'Gemini 3 Pro (旗舰)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash (快速)',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      // === Gemini 2.5 (稳定版) ===
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'gemini-2.5-flash-lite',
        name: 'Gemini 2.5 Flash Lite (便宜)',
        capabilities: ['fast', 'general'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.perplexity,
    models: [
      {
        id: 'sonar-pro',
        name: 'Sonar Pro (联网搜索)',
        capabilities: ['search', 'general'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'sonar',
        name: 'Sonar (联网搜索)',
        capabilities: ['search', 'fast'],
        maxTokens: 4096,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
    ],
  },
  volcengine: {
    id: 'volcengine',
    name: '火山引擎 (豆包)',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.volcengine,
    models: [
      {
        id: 'doubao-1.5-pro-256k',
        name: 'Doubao 1.5 Pro 256K',
        capabilities: ['general', 'code', 'longContext'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'doubao-1.5-thinking-pro',
        name: 'Doubao 1.5 Thinking Pro',
        capabilities: ['reasoning', 'code'],
        maxTokens: 16384,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'doubao-seed-1-6-vision-250815',
        name: 'Doubao Seed 1.6 Vision',
        capabilities: ['vision', 'gui'],
        maxTokens: 16384,
        supportsTool: false,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
    ],
  },
  xiaomi: {
    id: 'xiaomi',
    name: '小米 MiMo (Token Plan)',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.xiaomi,
    models: [
      {
        id: 'mimo-v2.5-pro',
        name: 'MiMo v2.5 Pro (旗舰)',
        capabilities: ['general', 'code', 'reasoning', 'longContext', 'unlimited'],
        maxTokens: 131072, // max output；上下文 1M（见 CONTEXT_WINDOWS）
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'monthly',
      },
      {
        id: 'mimo-v2.5',
        name: 'MiMo v2.5',
        capabilities: ['general', 'code', 'reasoning', 'longContext', 'unlimited'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'monthly',
      },
      {
        id: 'mimo-v2-pro',
        name: 'MiMo v2 Pro',
        capabilities: ['general', 'code', 'reasoning', 'longContext', 'unlimited'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'monthly',
      },
      {
        id: 'mimo-v2-omni',
        name: 'MiMo v2 Omni (多模态)',
        capabilities: ['general', 'code', 'vision', 'reasoning', 'longContext', 'unlimited'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'monthly',
        visionCapabilities: {
          supportsBase64: true,
          supportsUrl: true,
          supportedFormats: ['png', 'jpeg', 'gif', 'webp'],
        },
      },
    ],
  },
  longcat: {
    id: 'longcat',
    name: 'LongCat',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.longcat,
    models: [
      {
        id: 'LongCat-2.0',
        name: 'LongCat 2.0',
        capabilities: ['general', 'code', 'reasoning', 'longContext'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'quota',
      },
      {
        id: 'LongCat-2.0-Preview',
        name: 'LongCat 2.0 Preview',
        capabilities: ['general', 'code', 'reasoning', 'longContext'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        thinking: { kind: 'toggle', defaultEnabled: true },
        costType: 'quota',
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter (中转)',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.openrouter,
    models: [
      // === Google Gemini 3 (2026最新) ===
      {
        id: 'google/gemini-3-flash-preview',
        name: 'Gemini 3 Flash (最新)',
        capabilities: ['general', 'code', 'vision', 'fast'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'google/gemini-3-pro-preview',
        name: 'Gemini 3 Pro (最强)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'google/gemma-3n-e2b-it:free',
        name: 'Gemma 3 (免费)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'free',
      },
      // === Anthropic Claude 4.5 (2026最新) ===
      {
        id: 'anthropic/claude-opus-4.5',
        name: 'Claude Opus 4.5 (旗舰)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'anthropic/claude-sonnet-4.5',
        name: 'Claude Sonnet 4.5',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'anthropic/claude-haiku-4.5',
        name: 'Claude Haiku 4.5 (快速)',
        capabilities: ['fast', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      // === OpenAI GPT-5.2 (2026最新) ===
      {
        id: 'openai/gpt-5.2',
        name: 'GPT-5.2 (最新)',
        capabilities: ['general', 'code', 'vision', 'reasoning'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'openai/gpt-5.2-codex',
        name: 'GPT-5.2 Codex (代码)',
        capabilities: ['code', 'reasoning'],
        maxTokens: 32768,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      // === Meta Llama 4 (2026最新) ===
      {
        id: 'meta-llama/llama-3.3-70b-instruct:free',
        name: 'Llama 3.3 70B (免费)',
        capabilities: ['general', 'code'],
        maxTokens: 8192,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'free',
      },
      {
        id: 'meta-llama/llama-4-maverick',
        name: 'Llama 4 Maverick (最新)',
        capabilities: ['general', 'code', 'vision'],
        maxTokens: 131072,
        supportsTool: true,
        supportsVision: true,
        supportsStreaming: true,
        costType: 'payg',
      },
      // === DeepSeek V3.2 (2026最新) ===
      {
        id: 'deepseek/deepseek-v3.2',
        name: 'DeepSeek V3.2 (最新)',
        capabilities: ['general', 'code'],
        maxTokens: 65536,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
      {
        id: 'deepseek/deepseek-r1-0528:free',
        name: 'DeepSeek R1 (免费推理)',
        capabilities: ['reasoning', 'code'],
        maxTokens: 65536,
        supportsTool: false,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'free',
      },
    ],
  },
  custom: {
    id: 'custom',
    name: 'Custom Provider',
    requiresApiKey: true,
    baseUrl: MODEL_API_ENDPOINTS.custom,
    models: [
      {
        id: 'custom-model',
        name: 'Custom Model',
        capabilities: ['general', 'code'],
        maxTokens: 16384,
        supportsTool: true,
        supportsVision: false,
        supportsStreaming: true,
        costType: 'payg',
      },
    ],
  },
};
