import { applyOverride } from '../registry';

export const FILE_WRITE_TOOL_DESCRIPTION = applyOverride(
  { id: 'tools.fileWrite', category: '工具描述', name: '文件写入工具描述', description: 'Write / Append 工具的 prompt 描述' },
  `
## File Write Tools

- Use \`Write\` for new files or complete rewrites when the whole content is ready.
- \`Write\` and \`Append\` create parent directories automatically; when the user gives an explicit output path, write the file directly instead of spending a separate tool turn on \`mkdir\`.
- Use \`Append\` for very large generated artifacts: create the file with \`Write\`, append ordered chunks, and set \`final: true\` only on the last append. A complete medium-sized single-file app/game may be written in one \`Write\` call.
- If an \`Append\` chunk adds the closing tags or otherwise completes the deliverable, that call is the last append and must set \`final: true\`.
- Use \`Edit\` for precise changes to existing files after \`Read\`.
- Prefer \`Append\` over shell heredocs when assembling large HTML/CSS/JS, documents, fixtures, or generated data.
- For generated games or strong interactive HTML, the final file must include \`window.__GAME_META__\` / \`window.__INTERACTIVE_META__\` coverage metadata and \`window.__GAME_TEST__\` / \`window.__INTERACTIVE_TEST__\` with all five methods: \`start()\`, \`reset(levelOrScenario?)\`, \`snapshot()\`, \`step(inputState, frames?)\`, and \`runSmokeTest()\`. Assign the test contract as one direct plain object literal, e.g. \`window.__GAME_TEST__ = { start() { ... }, reset(levelOrScenario) { ... }, snapshot() { return {...}; }, step(inputState = {}, frames = 1) { ...; return this.snapshot(); }, runSmokeTest() { return { passed, checks, failures, coverage }; } };\`; do not put it in comments, a wrapper function, \`Object.assign\`, a class, or orphaned function tails. Metadata must include exact \`progressPlan\` or \`reachability\` steps with dispatchable inputs and snapshot metrics; do not use \`input: 'none'\`, and a generic \`progress\`, \`coverage\`, or string-array \`acceptance\` object is not enough. If metadata declares authored unit ids/keys/names, \`reset(levelOrScenario?)\` must accept those exact values plus numeric indexes. \`step()\` must accept declared semantic controls and real key codes. Real browser keyboard listeners must normalize \`event.code === 'Space'\` or \`event.key === ' '\` to the same \`Space\` state that \`step({ Space: true })\` uses. \`runSmokeTest()\` must report input-driven structured coverage for promised mechanics, rewards, risks, progress, and every authored level/scenario/segment when present, with \`checks\` and \`failures\` returned as string arrays; coverage fields must name evidence or use boolean maps, not numeric counts.
- For platformer games, metadata must also include \`gameplayMechanics\` with enemies, blocks, abilities, gates, and comboChallenge. The runtime test must prove stomp enemy, bump block, gain ability, unlock gate/route, and comboChallenge through before/after \`snapshot()\` changes or explicit input-driven coverage.
- Large canvas games must include responsive canvas or wrapper CSS (\`max-width\`, \`max-height\`, \`aspect-ratio\`, \`height:auto\`, or equivalent) so the whole playfield fits the browser viewport, including a 390px mobile viewport. The rendered CSS aspect ratio must match the canvas internal width/height; do not stretch a portrait internal canvas into a landscape box or the reverse. Do not rely on fixed 800px/900px width or max-height-only scaling that can still overflow horizontally, and do not cap wide desktop previews to a small centered playfield with large empty margins.
- Browser games should be authored to pass visual smoke in desktop, wide-desktop, and narrow/mobile viewports: nonblank canvas or visible DOM gameplay, primary game surface sized for the preview, rendered aspect ratio matches canvas internal resolution, actor visible, HUD framed, first screen includes reward/risk/goal cues, no horizontal canvas crop, and no obvious critical UI overlap.
- If the game is a stickman / 火柴人 game, the actor must be visually inspectable: readable head, torso, arms, legs, pose/animation, strong contrast, and a meaningful on-screen size. Do not accept a tiny thin line figure in an empty field as complete.
`,
);
