import type { KeybindingDefinition } from './types';

export const KEYBINDING_DEFINITIONS = [
  {
    id: 'app.toggle',
    label: '打开/隐藏应用',
    description: '从系统任意位置唤起或隐藏主窗口',
    category: 'global',
    scope: 'global',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
    risk: 'advanced',
  },
  {
    id: 'app.quickAsk',
    label: '快速提问',
    description: '唤起轻量输入框，快速向当前 Agent 提问',
    category: 'global',
    scope: 'global',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+Shift+A', win32: 'Ctrl+Shift+A', linux: 'Ctrl+Shift+A' },
    risk: 'advanced',
  },
  {
    id: 'session.new',
    label: '新建会话',
    description: '创建一个新的对话会话',
    category: 'global',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+N', win32: 'Ctrl+N', linux: 'Ctrl+N' },
  },
  {
    id: 'voice.toggle',
    label: '语音输入',
    description: '开始或停止语音输入',
    category: 'global',
    scope: 'global',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'appshot.capture',
    label: '截图问答',
    description: '捕捉当前屏幕或窗口并送入会话',
    category: 'global',
    scope: 'global',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+Cmd', win32: null, linux: null },
    risk: 'advanced',
  },
  {
    id: 'composer.send',
    label: '发送消息',
    description: '发送当前输入内容',
    category: 'sessionEditing',
    scope: 'composer',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Enter', win32: 'Enter', linux: 'Enter' },
  },
  {
    id: 'composer.newline',
    label: '换行',
    description: '在输入框中插入换行',
    category: 'sessionEditing',
    scope: 'composer',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Shift+Enter', win32: 'Shift+Enter', linux: 'Shift+Enter' },
  },
  {
    id: 'composer.focus',
    label: '聚焦输入框',
    description: '把焦点移动到消息输入框',
    category: 'sessionEditing',
    scope: 'composer',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+L', win32: 'Ctrl+L', linux: 'Ctrl+L' },
  },
  {
    id: 'composer.slashMenu',
    label: '打开 Slash 菜单',
    description: '在输入区打开命令提示菜单',
    category: 'sessionEditing',
    scope: 'composer',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: '/', win32: '/', linux: '/' },
  },
  {
    id: 'commandPalette.open',
    label: '打开命令面板',
    description: '搜索和执行应用命令',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+K', win32: 'Ctrl+K', linux: 'Ctrl+K' },
  },
  {
    id: 'session.stop',
    label: '停止生成',
    description: '停止当前运行中的任务',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Esc', win32: 'Esc', linux: 'Esc' },
  },
  {
    id: 'session.continue',
    label: '继续任务',
    description: '继续上一段可恢复的任务',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'session.retry',
    label: '重试上一步',
    description: '重新生成最后一条助手回复',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+Shift+R', win32: 'Ctrl+Shift+R', linux: 'Ctrl+Shift+R' },
  },
  {
    id: 'session.compact',
    label: '压缩上下文',
    description: '手动触发上下文压缩',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
    risk: 'expensive',
  },
  {
    id: 'session.clear',
    label: '清空当前对话',
    description: '清除当前会话消息，需要通过命令确认，不默认占用热键',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
    risk: 'destructive',
  },
  {
    id: 'session.previous',
    label: '上一个会话',
    description: '切换到上一个会话',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+[', win32: 'Ctrl+[', linux: 'Ctrl+[' },
  },
  {
    id: 'session.next',
    label: '下一个会话',
    description: '切换到下一个会话',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+]', win32: 'Ctrl+]', linux: 'Ctrl+]' },
  },
  {
    id: 'session.moveToBackground',
    label: '移至后台',
    description: '将当前运行中的会话移至后台并开启新会话',
    category: 'sessionEditing',
    scope: 'session',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+B', win32: 'Ctrl+B', linux: 'Ctrl+B' },
  },
  {
    id: 'settings.open',
    label: '打开设置',
    description: '打开应用设置',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+,', win32: 'Ctrl+,', linux: 'Ctrl+,' },
  },
  {
    id: 'artifacts.open',
    label: '打开 Artifacts',
    description: '打开当前会话的交付物面板',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'artifacts.preview',
    label: '预览交付物',
    description: '预览当前交付物',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'artifacts.export',
    label: '导出交付物',
    description: '导出当前交付物',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'artifacts.copy',
    label: '复制交付物',
    description: '复制当前交付物内容',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'artifacts.previousVersion',
    label: '上一个交付物版本',
    description: '切换到上一个交付物版本',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'artifacts.nextVersion',
    label: '下一个交付物版本',
    description: '切换到下一个交付物版本',
    category: 'delivery',
    scope: 'artifact',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'sidebar.toggle',
    label: '切换侧边栏',
    description: '显示或隐藏左侧会话栏',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+/', win32: 'Ctrl+/', linux: 'Ctrl+/' },
  },
  {
    id: 'dag.toggle',
    label: '切换 DAG 面板',
    description: '显示或隐藏任务 DAG 可视化面板',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+D', win32: 'Ctrl+D', linux: 'Ctrl+D' },
  },
  {
    id: 'workspace.toggle',
    label: '切换工作区',
    description: '显示或隐藏工作区面板',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+E', win32: 'Ctrl+E', linux: 'Ctrl+E' },
  },
  {
    id: 'statusRail.toggle',
    label: '切换任务面板',
    description: '显示或隐藏右侧任务状态面板',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: true,
    defaultHotkeys: { darwin: 'Cmd+J', win32: 'Ctrl+J', linux: 'Ctrl+J' },
  },
  {
    id: 'browser.open',
    label: '打开浏览器工作台',
    description: '打开 Browser 工作台',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'computerUse.open',
    label: '打开 Computer Use',
    description: '打开 Computer Use 工作台',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'replay.open',
    label: '打开 Replay',
    description: '打开当前会话回放',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'reviewQueue.open',
    label: '打开 Review Queue',
    description: '打开评审队列',
    category: 'workbench',
    scope: 'workbench',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'files.attach',
    label: '添加文件/附件',
    description: '打开文件附件选择器',
    category: 'workbench',
    scope: 'composer',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'settings.keybindings',
    label: '打开快捷键设置',
    description: '打开快捷键设置页',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'settings.mcp',
    label: '打开 MCP 设置',
    description: '打开 MCP 服务器设置',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'settings.skills',
    label: '打开 Skills 设置',
    description: '打开 Skills 设置',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'settings.plugins',
    label: '打开插件设置',
    description: '打开插件设置',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
  {
    id: 'settings.usage',
    label: '打开使用量',
    description: '打开模型和成本使用量',
    category: 'settings',
    scope: 'settings',
    configurable: true,
    enabledByDefault: false,
    defaultHotkeys: { darwin: null, win32: null, linux: null },
  },
] as const satisfies KeybindingDefinition[];

export const KEYBINDING_DEFINITION_BY_ID = new Map(
  KEYBINDING_DEFINITIONS.map((definition) => [definition.id, definition])
);
