// Literal applyEffortControls outputs recorded before catalogue pass-through.
// Cases are shared because that function did not read the model.
import type { ModelReasoningEffort } from '../../../src/shared/contract/model';

export interface EffortControlsGoldenCase {
  thinkingBudget: number | undefined;
  reasoningEffort: ModelReasoningEffort | undefined;
}

export const GOLDEN_MODELS: readonly string[] = [
  'claude/claude-3-5-haiku-20241022',
  'claude/claude-3-5-sonnet-20241022',
  'claude/claude-haiku-4-5-20251001',
  'claude/claude-opus-4-7',
  'claude/claude-sonnet-4-20250514',
  'claude/claude-sonnet-4-6',
  'custom/custom-model',
  'deepseek/deepseek-chat',
  'deepseek/deepseek-coder',
  'deepseek/deepseek-flash',
  'deepseek/deepseek-reasoner',
  'deepseek/deepseek-v4-flash',
  'deepseek/deepseek-v4-pro',
  'gemini/gemini-2.5-flash',
  'gemini/gemini-2.5-flash-lite',
  'gemini/gemini-2.5-pro',
  'gemini/gemini-3-flash',
  'gemini/gemini-3-flash-preview',
  'gemini/gemini-3-pro',
  'gemini/gemini-3-pro-preview',
  'gemini/gemini-3.1-pro-preview',
  'grok/grok-4-1-fast-non-reasoning',
  'grok/grok-4-1-fast-reasoning',
  'groq/groq/compound',
  'groq/llama-3.1-8b-instant',
  'groq/meta-llama/llama-4-maverick-17b-128e-instruct',
  'groq/meta-llama/llama-4-scout-17b-16e-instruct',
  'groq/moonshotai/kimi-k2-instruct',
  'groq/openai/gpt-oss-20b',
  'local/codestral:22b',
  'local/deepseek-r1:32b',
  'local/deepseek-r1:7b',
  'local/gemma4:12b',
  'local/gemma4:27b',
  'local/llama4-scout:17b',
  'local/qwen2.5-coder:7b',
  'local/qwen3:32b',
  'local/qwen3:8b',
  'longcat/LongCat-2.0',
  'minimax/MiniMax-M2.5',
  'minimax/MiniMax-M2.7',
  'minimax/abab5.5-chat',
  'minimax/abab5.5s-chat',
  'minimax/abab6.5-chat',
  'minimax/abab6.5s-chat',
  'moonshot/kimi-k2-thinking',
  'moonshot/kimi-k2-turbo-preview',
  'moonshot/kimi-k2.5',
  'moonshot/kimi-k2.6',
  'moonshot/moonshot-v1-128k',
  'moonshot/moonshot-v1-32k',
  'moonshot/moonshot-v1-8k',
  'openai/gpt-4o',
  'openai/gpt-4o-mini',
  'openai/gpt-5.2',
  'openai/gpt-5.3-codex',
  'openai/gpt-5.4',
  'openai/gpt-5.4-mini',
  'openai/gpt-5.4-nano',
  'openai/gpt-5.5',
  'openai/gpt-5.5-pro',
  'openrouter/anthropic/claude-haiku-4.5',
  'openrouter/anthropic/claude-opus-4.5',
  'openrouter/anthropic/claude-sonnet-4.5',
  'openrouter/deepseek/deepseek-r1-0528:free',
  'openrouter/deepseek/deepseek-v3.2',
  'openrouter/google/gemini-3-flash-preview',
  'openrouter/google/gemini-3-pro-preview',
  'openrouter/google/gemma-3n-e2b-it:free',
  'openrouter/meta-llama/llama-3.3-70b-instruct:free',
  'openrouter/meta-llama/llama-4-maverick',
  'openrouter/openai/gpt-5.2',
  'openrouter/openai/gpt-5.2-codex',
  'perplexity/sonar',
  'perplexity/sonar-deep-research',
  'perplexity/sonar-pro',
  'perplexity/sonar-reasoning',
  'perplexity/sonar-reasoning-pro',
  'qwen/qvq-max',
  'qwen/qwen-coder-plus',
  'qwen/qwen-image-edit-max',
  'qwen/qwen-image-max',
  'qwen/qwen-max',
  'qwen/qwen-mt-turbo',
  'qwen/qwen-omni-turbo',
  'qwen/qwen-plus',
  'qwen/qwen-plus-latest',
  'qwen/qwen-turbo',
  'qwen/qwen-vl-max',
  'qwen/qwen-vl-ocr',
  'qwen/qwen2.5-7b-instruct-1m',
  'qwen/qwen3-asr-flash-realtime',
  'qwen/qwen3-coder',
  'qwen/qwen3-coder-flash',
  'qwen/qwen3-coder-plus',
  'qwen/qwen3-max',
  'qwen/qwen3-omni-flash',
  'qwen/qwen3-tts-flash',
  'qwen/qwen3-vl-flash',
  'qwen/qwen3-vl-plus',
  'qwen/qwen3.6-plus',
  'qwen/qwq-plus',
  'qwen/text-embedding-v4',
  'volcengine/doubao-1.5-pro-256k',
  'volcengine/doubao-1.5-thinking-pro',
  'volcengine/doubao-seed-1-6',
  'volcengine/doubao-seed-1-6-flash',
  'volcengine/doubao-seed-1-6-lite',
  'volcengine/doubao-seed-1-6-thinking',
  'volcengine/doubao-seed-1-6-vision-250815',
  'xiaomi/mimo-v2-omni',
  'xiaomi/mimo-v2-pro',
  'xiaomi/mimo-v2.5',
  'xiaomi/mimo-v2.5-pro',
  'zhipu/codegeex-4',
  'zhipu/cogvideox-flash',
  'zhipu/cogview-3-flash',
  'zhipu/glm-4-flash',
  'zhipu/glm-4.6v',
  'zhipu/glm-4.6v-flash',
  'zhipu/glm-4.7',
  'zhipu/glm-4.7-flash',
  'zhipu/glm-4.7-flashx',
  'zhipu/glm-5',
  'zhipu/glm-5.1',
  'zhipu/glm-5.3-flash',
];

export const GOLDEN_CASES: Record<string, EffortControlsGoldenCase> = {
  'low|true|none': { thinkingBudget: 2048, reasoningEffort: 'low' },
  'low|true|reasoningEffort': { thinkingBudget: 2048, reasoningEffort: 'high' },
  'low|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'low' },
  'low|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'low|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'low|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'low|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'low|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
  'medium|true|none': { thinkingBudget: 8192, reasoningEffort: 'medium' },
  'medium|true|reasoningEffort': { thinkingBudget: 8192, reasoningEffort: 'high' },
  'medium|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'medium' },
  'medium|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'medium|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'medium|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'medium|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'medium|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
  'high|true|none': { thinkingBudget: 16384, reasoningEffort: 'high' },
  'high|true|reasoningEffort': { thinkingBudget: 16384, reasoningEffort: 'high' },
  'high|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'high|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'high|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'high|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'high|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'high|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
  'xhigh|true|none': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'xhigh|true|reasoningEffort': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'xhigh|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'xhigh|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'xhigh|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'xhigh|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'xhigh|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'xhigh|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
  'max|true|none': { thinkingBudget: 65536, reasoningEffort: 'high' },
  'max|true|reasoningEffort': { thinkingBudget: 65536, reasoningEffort: 'high' },
  'max|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'max|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'max|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'max|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'max|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'max|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
  'ultra_code|true|none': { thinkingBudget: 49152, reasoningEffort: 'high' },
  'ultra_code|true|reasoningEffort': { thinkingBudget: 49152, reasoningEffort: 'high' },
  'ultra_code|true|thinkingBudget': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'ultra_code|true|both': { thinkingBudget: 32768, reasoningEffort: 'high' },
  'ultra_code|false|none': { thinkingBudget: undefined, reasoningEffort: undefined },
  'ultra_code|false|reasoningEffort': { thinkingBudget: undefined, reasoningEffort: undefined },
  'ultra_code|false|thinkingBudget': { thinkingBudget: undefined, reasoningEffort: undefined },
  'ultra_code|false|both': { thinkingBudget: undefined, reasoningEffort: undefined },
};
