import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  GAME_SKILL_GENERATION_CONTRACT,
  GAME_SKILL_REPAIR_HINTS,
} from '../../../../../src/host/agent/runtime/game/generatedSkillContent';

const REPO_ROOT = path.resolve(__dirname, '../../../../../');
const GENERATED_PATH = path.join(REPO_ROOT, 'src/host/agent/runtime/game/generatedSkillContent.ts');

describe('generate-game-skill-content', () => {
  it('generates non-empty platformer and runner skill maps from real SKILL.md files', () => {
    execFileSync('node', ['scripts/generate-game-skill-content.mjs'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    });

    const generatedSource = fs.readFileSync(GENERATED_PATH, 'utf8');
    expect(generatedSource).toContain('AUTO-GENERATED by scripts/generate-game-skill-content.mjs');
    expect(generatedSource).toContain('platformer');
    expect(generatedSource).toContain('runner');

    expect(GAME_SKILL_GENERATION_CONTRACT.platformer).toContain('Translate genre/reference into mechanics');
    expect(GAME_SKILL_GENERATION_CONTRACT.platformer).toContain('nearby authored smoke scenarios');
    expect(GAME_SKILL_GENERATION_CONTRACT.runner).toContain('Player auto-moves along `forwardAxis`');
    expect(GAME_SKILL_GENERATION_CONTRACT.runner).toContain('legitimate empty / "none" input');
    expect(GAME_SKILL_REPAIR_HINTS.platformer).toContain('missing_gameplay_mechanics');
    expect(GAME_SKILL_REPAIR_HINTS.runner).toContain('runner_no_distance_progression');
  });
});
