// ============================================================================
// slidesGenerator - 设计 tab 厚版演示稿生成 service（二期 MVP）
// ============================================================================
// 把现有 PPT 引擎（src/main/tools/media/ppt/*）的「确定性大纲 → 真排版 deck」核心
// 从 agent 工具 executePptGenerate 中抽出，供设计 tab IPC 直调——不经工具调用语义、
// 不调 LLM/研究/配图/VLM（那些是付费可选增强，留待后续增量）。
//
// 复刻 pptGenerate.ts:498-708 的 legacy（SlideData[]）路径，去掉 ToolContext/
// modelCallback/artifact/权限耦合。引擎纯核函数直接 import 复用，零拷贝。
// ============================================================================

import type PptxGenJS from 'pptxgenjs';
import type { ChartMode, SlideData, SlideImage } from '../../tools/media/ppt/types';
import { getThemeConfig } from '../../tools/media/ppt/themes';
import { outlineToSlideData, parseContentToSlides } from '../../tools/media/ppt/parser';
import { registerSlideMasters } from '../../tools/media/ppt/slideMasters';
import { selectMasterAndLayout, fillSlide, resetLayoutRotation } from '../../tools/media/ppt/layouts';

// pptxgenjs 是 CJS——走 require 取构造器（与 pptGenerate / pptxExport 同款）。
type PptxGenJSConstructor = new () => PptxGenJS;
function getPptxGenJS(): PptxGenJSConstructor {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const moduleValue: unknown = require('pptxgenjs');
  return moduleValue as PptxGenJSConstructor;
}

const DEFAULT_SLIDES_COUNT = 10;
const DEFAULT_THEME = 'neon-green';

export interface SlidesDeckInput {
  /** 演示稿主题 / 需求描述。 */
  topic: string;
  /** 期望页数（含封面/结尾），默认 10。 */
  slidesCount?: number;
  /** 主题样式键，未知值回退默认；默认 'neon-green'。 */
  theme?: string;
  /** 可选 Markdown 正文：提供则按它切页，优先于 topic 模板大纲。 */
  content?: string;
}

export interface SlidesDeckResult {
  /** PPTX nodebuffer（调用方负责写盘 / 下载）。 */
  buffer: Buffer;
  /** 实际生成的页数。 */
  slidesCount: number;
}

/**
 * 生成厚版演示稿 deck（真排版引擎，非图片塞 PPT）。
 * 当前 MVP：确定性大纲（或 Markdown 切页）→ 注册 8 类 master → 逐页 fillSlide → nodebuffer。
 * 不调任何付费模型；topic 为空抛可读错误。
 */
export async function generateSlidesDeck(input: SlidesDeckInput): Promise<SlidesDeckResult> {
  const topic = (input.topic ?? '').trim();
  if (!topic) {
    throw new Error('生成演示稿需要主题（topic 不能为空）');
  }
  const count = input.slidesCount && input.slidesCount > 0 ? input.slidesCount : DEFAULT_SLIDES_COUNT;
  const themeConfig = getThemeConfig(input.theme ?? DEFAULT_THEME);

  // 内容通道：有 Markdown 正文则按它切页，否则用确定性 SCQA 模板大纲。
  const content = input.content?.trim();
  const slides: SlideData[] = content
    ? parseContentToSlides(content, count)
    : outlineToSlideData(topic, count);

  const Pptx = getPptxGenJS();
  const pptx = new Pptx();
  pptx.author = 'Agent Neo';
  pptx.title = topic;
  pptx.subject = topic;
  pptx.company = 'Generated by Agent Neo';

  // ⑥ 注册 master + ⑦ 逐页组装（复刻 pptGenerate legacy 路径，无图片/图表注入）。
  registerSlideMasters(pptx, themeConfig);
  resetLayoutRotation();

  const noImages: SlideImage[] = [];
  for (let i = 0; i < slides.length; i++) {
    const slideData = slides[i];
    const { master, layout, chartData } = selectMasterAndLayout(slideData, false, 'auto' as ChartMode);
    const slide = pptx.addSlide({ masterName: master });
    fillSlide(pptx, slide, slideData, themeConfig, layout, i, chartData, noImages);
  }

  const out = await pptx.write({ outputType: 'nodebuffer' });
  return { buffer: Buffer.from(out as Uint8Array), slidesCount: slides.length };
}
