import { promises as fs } from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { SkillValidationError } from '../../../../src/shared/contract/agentSkill';
import {
  parseSkillMd,
  parseSkillMetadataOnly,
} from '../../../../src/main/services/skills/skillParser';

describe('skillParser allowed-tools validation', () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'skill-parser-'));
  });

  afterEach(async () => {
    await fs.rm(tmpDir, { recursive: true, force: true });
  });

  async function writeSkill(frontmatter: string): Promise<void> {
    await fs.writeFile(
      path.join(tmpDir, 'SKILL.md'),
      [
        '---',
        'name: test-skill',
        'description: Test skill',
        frontmatter,
        '---',
        '',
        'Use tools.',
        '',
      ].join('\n'),
      'utf-8',
    );
  }

  it('accepts tool names, MCP-style names, and scoped Bash prefixes', async () => {
    await writeSkill([
      'allowed-tools:',
      '  - Bash',
      '  - read_file',
      '  - browser_action.upload_file',
      '  - mcp__demo__list_items',
      '  - Bash(git:*)',
    ].join('\n'));

    const parsed = await parseSkillMd(tmpDir, 'builtin');

    expect(parsed.allowedTools).toEqual([
      'Bash',
      'read_file',
      'browser_action.upload_file',
      'mcp__demo__list_items',
      'Bash(git:*)',
    ]);
  });

  it('splits comma-separated string values generated by combo recordings', async () => {
    await writeSkill('allowed-tools: "Bash,Read,mcp__demo__list_items"');

    const parsed = await parseSkillMetadataOnly(tmpDir, 'project');

    expect(parsed.allowedTools).toEqual([
      'Bash',
      'Read',
      'mcp__demo__list_items',
    ]);
  });

  it('rejects malformed or shell-like scoped prefixes', async () => {
    await writeSkill('allowed-tools: ["Bash(rm -rf /:*)"]');

    await expect(parseSkillMd(tmpDir, 'builtin')).rejects.toMatchObject({
      name: 'SkillValidationError',
      field: 'allowed-tools',
      value: 'Bash(rm -rf /:*)',
    } satisfies Partial<SkillValidationError>);
  });

  it('rejects non-string entries instead of silently dropping them', async () => {
    await writeSkill([
      'allowed-tools:',
      '  - Bash',
      '  - 123',
    ].join('\n'));

    await expect(parseSkillMetadataOnly(tmpDir, 'project')).rejects.toMatchObject({
      name: 'SkillValidationError',
      field: 'allowed-tools',
      value: 123,
    } satisfies Partial<SkillValidationError>);
  });
});
